### ISSUE TITLE
Avoid hardcoded values in RSS template. Take values like...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#1009]
The puzzle `1004-e3426e23` from #1004 has to be resolved: 

https://github.com/fidals/shopelectro/blob/235fbccbc52e368038419262bc8f4ae895afea0c/templates/prices/price.rss#L7-L8

The puzzle was created by duker33 on 31-Oct-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
required DB values are living at the index flat Page: `FlatPage.objects.get(slug='')`

**Comment by 0pdd** [comment]
The puzzle `1004-e3426e23` has disappeared from the source code, that's why I closed this issue. //cc @artemiyds2 @duker33
