### ISSUE TITLE
Update prices separately

### ISSUE THREAD

**Issue by artemiy312** [fidals/shopelectro#1022]
We update price files only after successful catalog data update. Sometimes we have struggle with data update, but we still need to update price files, otherwise we will get penalties from aggregators.

We should make the price files update independent of the catalog data update.
We can try these approaches:
1) Update files in separate celery cron task
2) Update files in finally block of update_catalog task

**Comment by artemiy312** [comment]
The first approach seems simpler, but it will increase inconsistency time interval between files and catalog data.  
@duker33 Is it possible to increase that interval?

**Comment by duker33** [comment]
@artemiy312 , inconsistency time interval is not big a problem. We can just decrease the whole interval for full prices
