### ISSUE TITLE
Resolve PDD bug

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#171]
Псосле мержа pr#170 мне на почту пришло сообщение, что pdd сломался.
Ниже полная копия письма.
Мб пофикси наш код, мб заводи issue на проекте 0pdd

----------------
I wasn't able to retrieve PDD puzzles from the code base and submit them to GitHub. If you think that it's a bug on your our side, please submit it to yegor256/0pdd):

set -x;set -e;set -o pipefail;cd /tmp/0pdd20170930-4-17mf2de/fidals/shopelectro && pdd -q -f /tmp/pdd.xml20170930-13039-gz5m4k: pid 13062 exit 1 (not zero):

set -e
set -o pipefail
cd /tmp/0pdd20170930-4-17mf2de/fidals/shopelectro
pdd -q -f /tmp/pdd.xml20170930-13039-gz5m4k
/app/vendor/bundle/ruby/2.3.0/gems/pdd-0.17.6/lib/pdd/source.rb:146:in rescue in puzzles': ["in /tmp/0pdd20170930-4-17mf2de/fidals/shopelectro/shopelectro/tests/tests_commands.py", #<PDD::Error: @todo found, but puzzle can't be parsed in line #25>] (PDD::Error) from /app/vendor/bundle/ruby/2.3.0/gems/pdd-0.17.6/lib/pdd/source.rb:144:inpuzzles'
from /app/vendor/bundle/ruby/2.3.0/gems/pdd-0.17.6/lib/pdd.rb:97:in block (3 levels) in xml' from /app/vendor/bundle/ruby/2.3.0/gems/pdd-0.17.6/lib/pdd.rb:96:ineach'
from /app/vendor/bundle/ruby/2.3.0/gems/pdd-0.17.6/lib/pdd.rb:96:in block (2 levels) in xml' from /app/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.8.0/lib/nokogiri/xml/builder.rb:391:ininsert'
from /app/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.8.0/lib/nokogiri/xml/builder.rb:375:in method_missing' from /app/vendor/bundle/ruby/2.3.0/gems/pdd-0.17.6/lib/pdd.rb:95:inblock in xml'
from /app/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.8.0/lib/nokogiri/xml/builder.rb:293:in initialize' from /app/vendor/bundle/ruby/2.3.0/gems/pdd-0.17.6/lib/pdd.rb:93:innew'
from /app/vendor/bundle/ruby/2.3.0/gems/pdd-0.17.6/lib/pdd.rb:93:in xml' from /app/vendor/bundle/ruby/2.3.0/gems/pdd-0.17.6/bin/pdd:63:in<top (required)>'
from /app/vendor/bundle/ruby/2.3.0/bin/pdd:22:in load' from /app/vendor/bundle/ruby/2.3.0/bin/pdd:22:in'
Please, copy and paste this stack trace to GitHub:

set -x;set -e;set -o pipefail;cd /tmp/0pdd20170930-4-17mf2de/fidals/shopelectro && pdd -q -f /tmp/pdd.xml20170930-13039-gz5m4k: pid 13062 exit 1 (not zero):
+ set -e
+ set -o pipefail
+ cd /tmp/0pdd20170930-4-17mf2de/fidals/shopelectro
+ pdd -q -f /tmp/pdd.xml20170930-13039-gz5m4k
/app/vendor/bundle/ruby/2.3.0/gems/pdd-0.17.6/lib/pdd/source.rb:146:in `rescue in puzzles': ["in /tmp/0pdd20170930-4-17mf2de/fidals/shopelectro/shopelectro/tests/tests_commands.py", #<PDD::Error: @todo found, but puzzle can't be parsed in line #25>] (PDD::Error)
	from /app/vendor/bundle/ruby/2.3.0/gems/pdd-0.17.6/lib/pdd/source.rb:144:in `puzzles'
	from /app/vendor/bundle/ruby/2.3.0/gems/pdd-0.17.6/lib/pdd.rb:97:in `block (3 levels) in xml'
	from /app/vendor/bundle/ruby/2.3.0/gems/pdd-0.17.6/lib/pdd.rb:96:in `each'
	from /app/vendor/bundle/ruby/2.3.0/gems/pdd-0.17.6/lib/pdd.rb:96:in `block (2 levels) in xml'
	from /app/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.8.0/lib/nokogiri/xml/builder.rb:391:in `insert'
	from /app/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.8.0/lib/nokogiri/xml/builder.rb:375:in `method_missing'
	from /app/vendor/bundle/ruby/2.3.0/gems/pdd-0.17.6/lib/pdd.rb:95:in `block in xml'
	from /app/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.8.0/lib/nokogiri/xml/builder.rb:293:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/gems/pdd-0.17.6/lib/pdd.rb:93:in `new'
	from /app/vendor/bundle/ruby/2.3.0/gems/pdd-0.17.6/lib/pdd.rb:93:in `xml'
	from /app/vendor/bundle/ruby/2.3.0/gems/pdd-0.17.6/bin/pdd:63:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/pdd:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/pdd:22:in `<main>'

/app/objects/exec.rb:41:in `block in run'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/open3.rb:205:in `popen_run'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/open3.rb:95:in `popen3'
/app/objects/exec.rb:39:in `run'
/app/objects/git_repo.rb:58:in `xml'
/app/objects/puzzles.rb:37:in `deploy'
/app/objects/job.rb:40:in `proceed'
/app/objects/job_starred.rb:33:in `proceed'
/app/objects/job_recorded.rb:31:in `proceed'
/app/objects/job_emailed.rb:34:in `proceed'
/app/objects/job_commiterrors.rb:34:in `proceed'
/app/objects/job_detached.rb:49:in `block in exclusive'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/app/objects/job_detached.rb:47:in `exclusive'
/app/objects/job_detached.rb:37:in `block in proceed'
/app/objects/job_detached.rb:37:in `fork'
/app/objects/job_detached.rb:37:in `proceed'
/app/0pdd.rb:335:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1632:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1632:in `block in compile!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:991:in `block (3 levels) in route!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1010:in `route_eval'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:991:in `block (2 levels) in route!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1037:in `block in process_route'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1035:in `catch'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1035:in `process_route'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:989:in `block in route!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:988:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:988:in `route!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1094:in `block in dispatch!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `block in invoke'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `catch'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `invoke'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1091:in `dispatch!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `block in call!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `block in invoke'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `catch'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `invoke'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `call!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:913:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/xss_header.rb:18:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/path_traversal.rb:16:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/json_csrf.rb:26:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/frame_options.rb:31:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/logger.rb:15:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/common_logger.rb:33:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:231:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:224:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:194:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1955:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1499:in `block in call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1726:in `synchronize'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1499:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/handler/webrick.rb:86:in `service'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by artemiy312** [comment]
Пофиксил. Использовался невалидный формат задачи.
# @todo Использовать файл с фикстурами. Скачивание файлов тестировать отдельно. ->
'''
@todo Использовать файл с фикстурами.
 Скачивание файлов тестировать отдельно.
'''
