### ISSUE TITLE
Autobuild local env

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#176]
Сейчас чтобы развернуть локальную среду, нужно покопаться и страдать. Сам только вчера страдал пару бакетов (5ч)

Сделай какой-нить sh с автосозданием рабочей среды на локали. Много не хватает, вот что бросилось мне в глаза:
- local.py+.env копируй из local.py.dist+.env.dist. В кач-ве ключей юзай или случайные или дефолтные значения (опишем в #229)
- ~скачивай и разворачивай на локали боевую базу. В нашем случае так будет проще всего. Для этого можно развернуть что-то типа репы с последним дампом базы. Доступ к репе - по открытым ключам, которые нам скидывают Прогеры. Например тот же ключ, что и для Гита, отлично подойдёт. Или просто по паролю~
- ~разворачивай (или скачивай) на локали боевую статику. Ту, что во front/build~
- ~по включенной опции скачивай боевую media. Для этого подойдёт диалог/опции при запуске sh~
- ~всё это документи в нашем rst~

**Comment by dveselov** [comment]
Зависит от https://github.com/fidals/shopelectro/pull/205

**Comment by duker33** [comment]
@dveselov , зависимости лучше писать в самое начало тела задачи. Чтоб было понятно читать ли её вообще

**Comment by duker33** [comment]
@dveselov , это вроде просто дубль, го закроем с тегом duplicate:
https://github.com/fidals/shopelectro/issues/204

**Comment by duker33** [comment]
тогда в этой задаче остаётся только авто-копирование .env -> .env.dist
Остальное Дима реализовал здесь
https://github.com/fidals/shopelectro/pull/205

**Comment by duker33** [comment]
как копировать .env.dist -> .env, опишу в файле инструкции в #229
