### ISSUE TITLE
Move CI to our server

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#178]
Трэвис на беспланом серве билдит не очень.
Сейчас у нас один travis ci идёт ~20 мин. Учитывая, что мы будем оперировать задачами с оценкой по 15-30 мин, это слишком долго.
Кроме того, Трэвис часто отваливается по ресурсам, что плодит нам в ci рандомные ошибки. А это очень дорого, конечно же.

Исследуй разные коробки. Например travis, jenkins, team-city и тд.
Нам нужно что-то простенькое, позже развернём коробку на своём серве.

Результат задачи - отчёт по исследованию здесь в комментах, решение по инструменту принято, создана новая задача по внедрению инструмента

Концы от нашего хоста бери у @duker33

**Comment by dveselov** [comment]
Рассматриваются только opensource решения?

[Jenkins CI](https://jenkins.io) - хороший вариант (в последнее время он [очень сильно поменялся]( https://jenkins.io/projects/blueocean/)), развитое сообщество, есть тонны всяческих плагинов. Отпугивает - [какой-то странный синтаксис для pipelines](https://jenkins.io/doc/book/pipeline/) и общая сложность

[Drone CI](https://github.com/drone/drone) - написан на Go, используется похожий на travis конфигурационный файл, есть поддержка нескольких вариантов деплоя из коробки (например, может пригодится [обновление сервисов kubernetes](http://plugins.drone.io/mactynow/drone-kubernetes/), если мы выберем его в #177), умеет собирать докер-образы и пушить их в регистр, [тоже из коробки](http://plugins.drone.io/drone-plugins/drone-docker/).

**Comment by duker33** [comment]
@dveselov , имхо Drone CI выглядит неплохо.
@artemiy312 , что думаешь?

**Comment by artemiy312** [comment]
@duker33 , да я бы тоже предпочел Drone CI

**Comment by duker33** [comment]
@dveselov , пару моментов по процессу:

- знаю из чатика, что ты настроил Drone CI на прод-серве и осталось нашлёпать для него конфиг. Пиши о таких вещах в комменты плз. Чтобы было видно всем и мы сами могли легко вспомнить что происходит с задачей
- для задачи "сделать drone CI конфиг" по канонам pdd нужно поступить так: создаёшь болванку конфиг-файла, пишешь в неё `@todo "Создай конфиг, Drone CI уже есть на прод-серве"`. Создай плз. Ну или я сам позже доблестно ворвусь и создам

**Comment by 0pdd** [comment]
@duker33 all 2 puzzles are solved here: [#208](https://github.com/fidals/shopelectro/issues/208), [#210](https://github.com/fidals/shopelectro/issues/210).
