### ISSUE TITLE
Create list of e-commerce complicated features

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#187]
Обязательна для [trello tw#22](https://trello.com/c/M907hYK2/22-rf-ecommerce-arch)

Составь список сложных фичей, которые относятся к разделу ecommerce.

Укажи для ТехРайтера где лежит код для каждой из них.

Вот список, который у меня в голове. Скорее всего он неполный:
- выгрузка товаров из 1С
- корзина
- цикл заказа

Результат задачи - коммент к этой issue, или rst-дока. Как посчитаешь нужным

**Comment by dveselov** [comment]
Выгрузка товаров - https://github.com/fidals/shopelectro/blob/master/shopelectro/management/commands/update_catalog.py (с FTP скачивается выгрузка из 1C в формате XML, производится разбор и добавление/удаление/обновление затронутых продуктов и их характеристик)

Обновление прайслистов для Яндекс.Маркета - https://github.com/fidals/shopelectro/blob/master/shopelectro/management/commands/price.py (обычно происходит после обновления каталога)

Обновление прайслистов в формате Excel - https://github.com/fidals/shopelectro/blob/master/shopelectro/management/commands/excel.py

Базовая корзина - https://github.com/fidals/refarm-site/blob/master/ecommerce/cart.py (частично переопределяется в SE - используется пересчет цены в зависимости от объема закупки: https://github.com/fidals/shopelectro/blob/master/shopelectro/cart.py)

Базовая модель заказа - https://github.com/fidals/refarm-site/blob/master/ecommerce/models.py (в SE туда добавляется несколько полей: https://github.com/fidals/shopelectro/blob/master/shopelectro/models.py#L114)

Стандартные вьюшки для заказа и корзины - https://github.com/fidals/refarm-site/blob/master/ecommerce/views.py (используются в SE с минимальными изменениями, переопределяются только модифицированные модели корзины и заказа: https://github.com/fidals/shopelectro/blob/master/shopelectro/views/ecommerce.py)

Вьюшка, формирующая данные для оплаты через Яндекс.Кассу - https://github.com/fidals/shopelectro/blob/master/shopelectro/views/ecommerce.py#L93
(этап номер два из схемы платежа: https://tech.yandex.ru/money/doc/payment-solution/payment-process/payments-receipt-docpage/)

Сервисные вьюшки для проверки платежей Яндекс.Кассы: https://github.com/fidals/shopelectro/blob/master/shopelectro/views/service.py (этап пять и далее из схемы платежа https://tech.yandex.ru/money/doc/payment-solution/payment-process/payments-receipt-docpage/)

#### Не самые сложные вещи, но о них тоже стоит упомянуть:

Рассылка почтовых уведомлений - https://github.com/fidals/refarm-site/blob/master/ecommerce/mailer.py (отправляются после сделанного заказа, в SE меняется только шаблон письма)

**Comment by duker33** [comment]
@dveselov , собственно, у нас есть результат задачи - коммент. Закрываем
