### ISSUE TITLE
SE yml fix delivery 3k -> 5k

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#192]
[origin trello task](https://trello.com/c/LyLVDakS/298-se-%D0%BF%D1%80%D0%B0%D0%B2%D1%8C-yml)

Внезапно обноружили, что через фид передается( в теге <sales_notes>) неверная инфа о доставке.
Исправь на 5к.

**Comment by themygit** [comment]
@duker33 закрыли же ?

**Comment by duker33** [comment]
@themygit , да, я криво привязал к коду, вот и не закрылось.
