### ISSUE TITLE
STB Category ChoiseField autocomplete

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#193]
[trello origin](https://trello.com/c/9h2YIHUj/296-stb-category-choisefield-autocomplete)

В Админке добавляем автокомплит при создании категорий http://prntscr.com/eepm4q

Речь идёт о Category EditPage. Вот пример:
http://www.stroyprombeton.ru/admin/stroyprombeton/categorypage/15312/change/

Если нажмёшь на поле "Родитель", узнаешь наш скрин. Сейчас там неудобненько, т.к. ~200 категорий нужно скроллить, чтобы найти нужную для выбора

**Comment by artemiy312** [comment]
Задача не относится к этому проекту. Перенес ее сюда https://github.com/fidals/stroyprombeton/issues/151
