### ISSUE TITLE
Improve "load more" button's UX

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#194]
[trello origin](https://trello.com/c/P7bGkuMF/285-%D0%BF%D0%BE%D0%B4%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B0-%D1%82%D0%BE%D0%B2%D0%B0%D1%80%D0%BE%D0%B2-%D0%B2-%D0%BA%D0%B0%D1%82%D0%B0%D0%BB%D0%BE%D0%B3%D0%B5-se)

Например https://www.shopelectro.ru/catalog/categories/novogodnie-tovary/
Клик "Загрузить еще" - получаем пачку товаров и фокус на нижнем ряду новой пачки. То есть надо скролить вверх, чтобы просмотреть эту всю пачку. А потом опять вниз, если хочешь "Загрузить еще". Лучше видеть новую пачку с первого ряда (кнопка "Загрузить еще" уходит вниз)

**Comment by dveselov** [comment]
Уже сделано, вроде бы.

**Comment by duker33** [comment]
ноуп, на проде воспроизводится
