### ISSUE TITLE
SE Iterate tags in templates

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#195]
[trello origin](https://trello.com/c/zulRj7lF/294-se-iterate-tags-in-templates)
[seo templates doc](https://docs.google.com/document/d/18DFBsuh6NT8hjyihOJ2bxw9zEe8z_070MBQrbAq0kvE/edit#)

**Проблема**
Сеошники после некоторых применений мультисв-в обнаружили заголовок *Блоки питания для ноутбуков устанавливает пользователь и от сети 220 В* [по этому линку](https://www.shopelectro.ru/catalog/categories/bloki-pitaniia-288/tags/ustanavlivaet-polzovatel-and-ot-seti-220-v/)

Получилось нехорошо. Предлагают сделать заголовок таким:
*Блоки питания для ноутбуков от сети 220 В, выбор выходного напряжения - устанавливает пользователь*

**Решение**
Чтобы переделать заголовок, нам нужно добавить в шаблон возможность указывать имя одного конкретного тега.

А решить это можно так: добавляем полноценный tags в seo-шаблоны.
Сейчас у нас только обрезанный tags.titles

**Comment by duker33** [comment]
@dveselov , я вот что подумал. А зачем нам `tags_metadata`? Го просто будем отдавать tags как есть, объектами? А в темплейтах будем обращаться к их полям

**Comment by dveselov** [comment]
@duker33 изначально нужно было передавать в шаблон только склеенную версию тегов, типа `аккумуляторы duracell или robiton`, а не сами теги. поэтому мы назвали это метаданными. если мы убираем метаданные, то куда мы денем склеенную версию тегов?

**Comment by duker33** [comment]
> если мы убираем метаданные, то куда мы денем склеенную версию тегов?

@dveselov , просто отдельным полем. Получится два поля:
`tag_titles` и `tags`

**Comment by duker33** [comment]
Дима аппрувнул мой pr, где я реализовал предложенную идею. Видимо мы договорились :)
Снимаю тег вопроса

**Comment by duker33** [comment]
инструкцию пофиксил. Осталось задеплоиться.
Но, пока не запустим Drone CI, не хочется ни мержиться, ни деплоиться

**Comment by duker33** [comment]
Drone CI замержили, снял hold

**Comment by duker33** [comment]
с этой задачей я ещё не закончил - нужно выдать СЕОшникам инструкцию и сбацать примерчик на проде

**Comment by duker33** [comment]
переназначил на себя, чтоб никого не смущало

**Comment by duker33** [comment]
Разобрались, наконец. 

Копия сообщеньки сеошникам:
```
расширенную работу с тегами релизнули.

Здесь в поле h1 пример шаблона тега:
https://www.shopelectro.ru/admin/pages/pagetemplate/7/change/

Страница от этого примера:
https://www.shopelectro.ru/catalog/categories/dlia-noutbukov-ot-seti-220-v/tags/ustanavlivaet-polzovatel/

Инструкция по тегам здесь:
https://docs.google.com/document/d/18DFBsuh6NT8hjyihOJ2bxw9zEe8z_070MBQrbAq0kvE/edit#heading=h.2sc5g9d5ub5s

Если будет тяжко писать шаблоны тегов самим - выставляйте ТЗ, наделаем шаблонов сами
```
