### ISSUE TITLE
Gen categories tags to sitemap

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#197]
Сейчас в sitemap выгружаются, помимо прочего, страницы категорий.
Выгружай не только страницы, но и все варианты их тегов.
Однако, не должно быть страниц, удовлетворяющих паттерну `*-or-*`

Пример страницы, которую нужно выгрузить в sitemap:
https://www.shopelectro.ru/catalog/categories/universalnye-ot-seti-12-v/tags/vanson/

Строчку `Disallow: /*-or-*` из `robots.txt` не выпиливай ни в коем случае

**Comment by dveselov** [comment]
Стоит обратить внимание на то, что в `robots.txt` есть [ограничение на часть страниц с тегами](https://www.shopelectro.ru/robots.txt):
```
Disallow: /*-or-*
```

**Comment by duker33** [comment]
> Стоит обратить внимание на то, что в robots.txt есть ограничение ...

@themygit , выпиливаем?

**Comment by themygit** [comment]
@duker33 да, лучше исключить.

**Comment by duker33** [comment]
> да, лучше исключить.

@themygit , эм, нес-ко двусмысленно звучит. Кароч выпиливаем строчку `Disallow: /*-or-*` из robots

**Comment by themygit** [comment]
@duker33 да, плохо написал, извиняюсь.
Строчку выпиливать нельзя. ибо заедут дубли и сер ребята нас покарают.
Нужно выпилить эти страницы(удовлетворяющие /*-or-*) при генерации sitemap
