### ISSUE TITLE
index.rst:86-86: Описать процесс развертывания боевых...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#201]
The puzzle `176-cb752cc3` (from #176) in [`doc/source/index.rst`](https://github.com/fidals/shopelectro/blob/master/doc/source/index.rst) (lines 86-86) has to be resolved: "Описать процесс развертывания боевых данных на локали"

The puzzle was created by Oleg Zyryanov on 19-Oct-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by dveselov** [comment]
Closed in https://github.com/fidals/shopelectro/pull/205
