### ISSUE TITLE
SE делай перелинковку в карточке товара 

### ISSUE THREAD

**Issue by themygit** [fidals/shopelectro#206]
Сеошники просят реализовать перелинковку в карточках товаров 

Текст ТЗ:
Свойства в карточке товара должны быть кликабельны и вести на соответствующую страницу тегов:
Например находясь в карте товара https://www.shopelectro.ru/catalog/products/4940/ и кликая на  AA http://prntscr.com/h3wn7f мы попадаем на страницу фильтров. Где показаны все батарейки типоразмера АА https://www.shopelectro.ru/catalog/categories/batareiki-256/tags/aa/

Пример сайта с таким функционалом https://goldinthecity.ru/kole/40857/

**Comment by duker33** [comment]
> го запустим в это TW. Добавим его в чат, поспрашивает.

@themygit , нет, только не в чат. Его ещё читаю я, не хочу наслаждаться интервью-переписками.
А для TW - задача в трелло с контактами кого интервьювить. Он(а) там уже сам(а) разберётся

Прочитнул описание. 90% речи - о Тегах (Мультисв-ва). Они у нас уже реализованы.
Просто нужно воткнуть некоторые линки с них на ProductPage.
Имхо ты сам перешлёпаешь это описание быстрее, чем будешь возиться с задачами для TW и их контролем/ожиданием

**Comment by themygit** [comment]
@duker33 переписал задачу.
