### ISSUE TITLE
.drone.yml:1-1: Определи оптимальное количество...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#210]
The puzzle `208-56cdec4f` (from #208) in [`.drone.yml`](https://github.com/fidals/shopelectro/blob/master/.drone.yml) (lines 1-1) has to be resolved: "Определи оптимальное количество параллельных тестов"

The puzzle was created by Dima Veselov on 30-Oct-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
результат задачи - коммент о том как вычислить оптимал в параллельных тестах.
Конечно же, могут быть нужны эксперименты на CI серве и локали

**Comment by 0pdd** [comment]
The puzzle `208-56cdec4f` has disappeared from the source code, that's why I closed this issue. //cc @artemiyds2 @duker33
