### ISSUE TITLE
SE Правь битые товары

### ISSUE THREAD

**Issue by themygit** [fidals/shopelectro#211]
Добавили товарам родительскую катерогию - перестали открываться.
Возможно товары были дублями и зашли несколько раз. Проверь.
Прогнал сайт Ксеной. получилось:

https://www.shopelectro.ru/catalog/products/6654/
https://www.shopelectro.ru/catalog/products/6655/
https://www.shopelectro.ru/catalog/products/6647/
https://www.shopelectro.ru/catalog/products/6650/
https://www.shopelectro.ru/catalog/products/6651/
https://www.shopelectro.ru/catalog/products/6652/
https://www.shopelectro.ru/catalog/products/6648/
https://www.shopelectro.ru/catalog/products/6649/
https://www.shopelectro.ru/catalog/products/6653/

а еще нашел вот что нашлось:
на странице https://www.shopelectro.ru/pages/navigation/contacts/ битый линк на https://www.shopelectro.ru/static/images/logo.svg
в фаиле https://www.shopelectro.ru/static/css/pages.min.be6cefb41927.css битый линк на https://www.shopelectro.ru/static/images/fancybox/fancybox_sprite_2x.4ac188774675.png и на https://www.shopelectro.ru/static/images/fancybox/fancybox_loading_2x.5bafaeb221ca.gif

**Comment by dveselov** [comment]
Починил товары вручную (у каждого было по три дубля)

**Comment by duker33** [comment]
@dveselov , и посмотри на битые линки тоже плз

**Comment by duker33** [comment]
прокликал линки товаров, с ними всё ок.
Закрываю задачу
