### ISSUE TITLE
models.py:240-242: - refactor Tag.serialize_* methods -...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#221]
The puzzle `195-08ad816e` (from #195) in [`shopelectro/models.py`](https://github.com/fidals/shopelectro/blob/master/shopelectro/models.py) (lines 240-242) has to be resolved: "- refactor Tag.serialize_* methods - they must take argument `List[Tag]` as well as `List[Tuple[TagGroup, Tag]]` - they should be standalone functions, not static methods"

The puzzle was created by duker33 on 13-Nov-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
погорячился с `30 mins`, сделал оценку в `1 hour`
