### ISSUE TITLE
SE fix yml feed

### ISSUE THREAD

**Issue by themygit** [fidals/shopelectro#228]
[export-log.xlsx](https://github.com/fidals/shopelectro/files/1487091/export-log.xlsx)

Валидатор  ругается на yml что мы отдаем в маркет.
Отчет во вложении 
Валидатор - https://webmaster.yandex.ru/tools/xml-validator/

**Comment by dveselov** [comment]
На данный момент валидатор не ругается: 
![](https://i.imgur.com/lCy7isG.png)

**Comment by duker33** [comment]
@themygit , валидатор не ругается. Помоги воспроизвести плз

**Comment by themygit** [comment]
@duker33 перестал. закрывай.
