### ISSUE TITLE
Change 1C export algo for Tags

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#232]
В этой задаче речь идёт только о файле тегов:
shopelectro/management/commands/_update_catalog/update_tags.py

27.11.18 Произошла неприятная история.
Контентщик выгрузил нес-ко тегов для гирлянд, но они пропали от нашей выгрузки.
Сейчас выгрузка Тегов просто сносит всё что есть и заново накатывает из 1С. Мы немного изменим эту политику.

Реализуй такой алгоритм:
- все Теги, что зашли из 1С, заливаем в базу с перезаписью
- все Теги, что есть в базе, но нет в 1С, не трогаем

**Comment by duker33** [comment]
@artemiy312 , видел, что ты замержил нынешний код выгрузки 11.04.17
Нужно понять один момент. Есть надежда, что ты помнишь о нём:

Зачем нужен delete() всех тегов, что были в базе, да не были в 1С?
Это чисто для бизнес-логики или из-за каких-то кривых данных в файлах 1С?

**Comment by artemiy312** [comment]
@duker33 
В момент выполнения задачи нужно было сделать синхронизацию данных с 1С, т.е. если данные создались/удалились/обновились нужно произвести те же операции на нашей базе. 
Удалялись только те теги/группы тегов, которых не было в xml выгрузке.

**Comment by duker33** [comment]
@artemiy312 , всё, понял. Теперь они будут оставаться.
Забьём ещё один гвоздь в концепт выгрузки 1С

**Comment by duker33** [comment]
prod already deletes tags. Maybe it's because wrong deploy.
Checking it

**Comment by duker33** [comment]
fixed
