### ISSUE TITLE
se-backup-restore.sh:6-9: - DB restore error on local env. How...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#234]
Required for #190 

-----

The puzzle `232-865d5cdb` (from #232) in [`etc/se-backup-restore.sh`](https://github.com/fidals/shopelectro/blob/master/etc/se-backup-restore.sh) (lines 6-9) has to be resolved: "- DB restore error on local env. How to reproduce: - launch this script - restart se-python container"

The puzzle was created by duker33 on 28-Nov-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by ezjikfrom** [comment]
Приступил к работе над задачей

**Comment by duker33** [comment]
acquire this task

**Comment by duker33** [comment]
backup system is totally broken now. And i see no reason to build it just for sites.
Cancel this task
