### ISSUE TITLE
SE yandex.yml генерится с ошибками

### ISSUE THREAD

**Issue by themygit** [fidals/shopelectro#240]
На почте опять куча писем с нотисами о том, что фид генерируется с ошибками 

`Ошибка: Отсутствует обязательный элемент picture. Для каждого предложения необходимо указать как минимум один элемент picture с ссылкой на изображение товара. (строка 1169, столбец 17)
Ошибка: Отсутствует обязательный элемент picture. Для каждого предложения необходимо указать как минимум один элемент picture с ссылкой на изображение товара. (строка 1783, столбец 17)
Ошибка: Отсутствует обязательный элемент picture. Для каждого предложения необходимо указать как минимум один элемент picture с ссылкой на изображение товара. (строка 2471, столбец 17)
Ошибка: Отсутствует обязательный элемент picture. Для каждого предложения необходимо указать как минимум один элемент picture с ссылкой на изображение товара. (строка 3581, столбец 17)
и тд`

**Comment by artemiy312** [comment]
@duker33 
maybe an error raises becouse we do not have any `product.page.images.all` in https://github.com/fidals/shopelectro/blob/master/templates/prices/pictures.yml and we should add `if` there.

**Comment by ivnglkv** [comment]
По-моему, здесь просто проблема в том, что яндексу обязательно нужны картинки для товаров в некоторых категориях: [описание тега picture](https://yandex.ru/support/partnermarket/picture.html). Или URL невалидный получается

**Comment by ivnglkv** [comment]
Мне кажется, что ошибка из-за того, что яндексу в каких-то категориях обязательно нужно изображение: [описание тега picture](https://yandex.ru/support/partnermarket/picture.html)

**Comment by ivnglkv** [comment]
@duker33 
А есть какой-нибудь тестовый набор данных для SE, чтобы проверить генерацию фида для яндекса? Или дамп реальных, если у вас так принято. Я вижу, что есть скрипт, который стучится на рабочий сайт за бекапами, но там логин от рута, поэтому не знаю, даете вы такое новичкам, или нет

**Comment by duker33** [comment]
> яндексу в каких-то категориях обязательно нужно изображение

@ivnglkv , да, видимо ты прав. Бери первую картинку первого товара-наследника категории. 
Если ни одной картинки нет, юзай логотип `front/images/logo.png`

> А есть какой-нибудь тестовый набор данных для SE, чтобы проверить генерацию фида для яндекса? 

У нас есть вот такая Django fixture `shopelectro/fixtures/dump.json` для тестов на данных.
Для фидов вроде даже есть автотесты и они юзают эти данные, если я всё верно помню.
В крайнем случае можешь сгенерить руками и забросить в валидатор Яндекса

**Comment by ivnglkv** [comment]
@duker33, а за нарушение пунктов
> - Недопустима ссылка на логотип магазина или «заглушку» (страницу, где написано «картинка отсутствует» и т. п.). 
> - По указанной ссылке должно размещаться изображение товара, соответствующего описанию предложения. Нельзя использовать изображение другого товара.

бан, или что-то в этом стиле не дадут, если заметят?

**Comment by artemiy312** [comment]
@ivnglkv @duker33 Можно убрать товары без картинок перечисленных категорий из yml файла и создать задачу, в которой нужно добавить в админку фильтр для товаров, которым необходимы изображения для ямаркета

**Comment by ivnglkv** [comment]
@artemiy312, согласен. Определять, каким категориям обязательно нужна картинка, через спец. поле в модели `Category`? И ошибка только с фидом яндекса, остальным отбрасывать товары без картинок не надо?

**Comment by duker33** [comment]
@ivnglkv , нене, никаких спецполей.

У категории в плане картинок мб только два состояния: "нет картинок" и "есть картинка".
Есть картинка - это если она есть у одного из товаров-наследников категории.

И для есть/нет картинок добавляем фильтр в Админку (в отдельной задаче, конечно).

А прямо здесь просто не включай в фид удаляй категории без картинок и товары без картинок

**Comment by ivnglkv** [comment]
@duker33 ок, понял. Спецполе, или какой-то другой вариант отражения в настройках я имел в виду к тому, что Яндекс не для всех категорий требует картинку у товара, следовательно какие-то товары без картинки можно оставлять

**Comment by duker33** [comment]
@ivnglkv , ух, какая там сложнота у Яндекса. Давай таки обойдёмся без спецполя. Чем их меньше, тем лучше для всех
