### ISSUE TITLE
Choose monitoring service

### ISSUE THREAD

**Issue by artemiy312** [fidals/shopelectro#247]
У нас периодически выключаются celery воркеры. Возможных причин может быть множество, вплоть до того, что мы забыли их включить. Поэтому, чтобы знать о таких ситуациях, как можно раньше нужно выбрать и интегрировать систему мониторинга.  

Скрин с выключенными celery воркерами на проде:
![default](https://user-images.githubusercontent.com/13870342/34293067-47dde6aa-e714-11e7-95e8-01a1d8f4f358.png)

**Comment by artemiy312** [comment]
@duker33 @dveselov 

Нужно выбрать сервис для этого. Предлагайте свои варианты :)

**Comment by artemiy312** [comment]
Из бесплатного мне нравится [prometheus](https://github.com/prometheus/prometheus)

**Comment by duker33** [comment]
у меня, к сожалению, полный провал касательно инструментов, поэтому здесь не смогу подсказать.
Про prometheus видел в spb_python-чатах, что он крут

**Comment by dveselov** [comment]
Я тоже за prometheus.

**Comment by artemiy312** [comment]
Нужно тогда определиться, что мы хотим мониторить помимо celery воркеров.

Мне кажется хорошей идеей следить за состоянием самих сайтов:
- определять сколько времени занимают запросы
- какой статус отправляется в ответ по определенным ресурсам (позволит забить тревогу в случае, если начнут сыпаться одни 404 или сообщать 500, можно придумать еще кучу разных случаев)

Это можно очень просто реализовать библиотекой для [джанги](https://github.com/korfuri/django-prometheus), но я не знаю, как это повлияет на конечную производительность.

Или расширением для [nginx](https://github.com/knyar/nginx-lua-prometheus), на случай если вариант с джангой будет сильно подкашивать производительность.

**Comment by duker33** [comment]
@artemiy312 , да, я считаю, что нам за глаза хватит кода ответа и времени отклика по опр урлам.
Список урлов - по одному на каждый тип страницы (category page, product page, news page, tag page, etc)
Выставим Прометею значения для этого всего, начиная с которых он начнёт алертить.
Алертить, кстати, имхо лучше в Телеграм. Он как-то понадёжнее, чем Слак и у него более агрессивные пуши на мобилки

**Comment by duker33** [comment]
продолжим в #259
