### ISSUE TITLE
docker-compose.yml:56-57: if Validate `.env` is full Is...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#250]
The puzzle `229-a984cd8e` from #229 has to be resolved:

https://github.com/fidals/shopelectro/blob/5308166c782497f51ba645587af67377e152720b/docker/docker-compose.yml#L56-L57

The puzzle was created by duker33 on 26-Dec-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
connected with #280
