### ISSUE TITLE
Add tags content (from 16.01)

### ISSUE THREAD

**Issue by themygit** [fidals/shopelectro#253]
На страницы с тегами нужно добавить seo тексты - описания

- Тексты: [линк](https://docs.google.com/document/d/1Jra_Z-7jLjnrG6HEDkuj-4_a1QXtDfxGH2NfEqD0fyY/edit#heading=h.mhprvbbcviki)

Перекрашивай в гугл-доке шрифт готовых текстов в серый

**Comment by duker33** [comment]
ждёт доков о templeate tags

**Comment by themygit** [comment]
https://docs.google.com/document/d/1SpVIOdvjdcYRSbAIJTfiZ_UBvkT4LCqgwqzvd1Zr_C8/edit  - 3 партия текстов

**Comment by duker33** [comment]
оценка норм.
Будем создавать подзадачи, если что

**Comment by duker33** [comment]
i'll create ad on freelansim.ru and do tech support.
Seo guys will check texts

**Comment by duker33** [comment]
created task. Link: https://freelansim.ru/tasks/204457

**Comment by duker33** [comment]
found content implementor and connected seo with him.
Task is finished
