### ISSUE TITLE
Улучшить билд систему

### ISSUE THREAD

**Issue by artemiy312** [fidals/shopelectro#269]
Зависит от #248 

----

Как показала практика, для новых разработчиков вникнуть в систему сборки оказалось одной из самых больших задач. Поэтому мы должны упростить ее.
- билдим образы только на CI -> пушим их на docker-hub -> разработчики пулят их у себя на компах. Это поможет избежать проблем со сборкой образов.
- задокументировать систему сборки. Если кому-то придется разбираться в ней, то это будет проще с документацией
- переименовать .env.dist в .env, чтобы не делать лишней работы
- монтировать контейнеры только внутрь проекта. Мы не должны монтировать ничего в корень системы (e.g. `/opt/database/shopelectro:/var/lib/postgresql/data` -> `../database/postgres:/var/lib/postgresql/data`). P.S. Актуально только для `docker-compose.yml`, т.е. для локальной разработки

В идеале процесс доставки зависимостей на компьютер разработчика будет таким:
```bash
docker-compose pull
docker-compose up
```

**Comment by duker33** [comment]
@artemiy312 , 

> билдим образы только на CI

сейчас основная проблема - это npm. Он по-разному разваливается на разных машинах.
И проблема в том, что, npm-зависимости ставятся при запуске контейнера, а не при билде образа.
В #248 мы собираемся это разрулить.
После неё этот пункт станет возможным, да.

> переименовать .env.dist в .env, чтобы не делать лишней работы

тут проблема в контроле версий. На локальной машине будет .env в вечном modified.
По-моему это не особо удобно.
Тут нужна (полу)интерактивная система чека .env-файла.
Если в нём нету какой-то настройки из шаблона (например `.env.dist`) или какого другого шаблона, он пишет предупреждения.
Эту штуку нам хорошо бы освоить и для всяких config.yml, которые часто встречаются в разных проектах.

С остальным согласен

**Comment by duker33** [comment]
задача не только (и не столько) о доках.
О доках будет только одна пдд-подзадача, поэтому сниму тег doc

**Comment by artemiy312** [comment]
@duker33 
>npm-зависимости ставятся при запуске контейнера, а не при билде

Да, нам нужно устанавливать зависимости на этапе билда.
Еще стоит задуматься о билде статики прямо в образ, чтобы мы могли пушить se-source вместе со статикой, чтобы потом не билдить ее на локале.

На CI это будет выглядеть:
1. Билдим образ nodejs с зависимостями
2. Билдим статику с помощью nodejs образа
3. Кладем собраную статику в se-source образ

На локале:
- `docker-compose pull se-source`
- `docker-compose up -d se-source` будет монтировать статику готовую к работе

Так же пора подумать о версионирование. Это упростит нашу работу :)

>Если в нём нету какой-то настройки из шаблона (например .env.dist) или какого другого шаблона, он пишет предупреждения.

`docker-compose` пишет варнинги, если ты используешь в .yml файле переменные, которых нет в .env файле. Так же мы можем кидать ошибки из мест, где мы используем эти переменные.

**Comment by duker33** [comment]
@artemiy312 , со статикой согласен.

> docker-compose пишет варнинги

это да, пишет. Просто можно было сделать покрасивее: писать "check your docker/.env file" и прерывать выполнение билда с ненулевым кодом.
Но если это кажется оверхедом, можем прост забить и ничего не делать. Оставим .env.dist как есть.
В readme написано, что его надо копипастить. Да и знание об env'ах - это область доков Докера, а не нашего проекта

**Comment by duker33** [comment]
в общем, забиваем на env'ы, снимаю discuss

**Comment by artemiy312** [comment]
@duker33 я уже реализовал нужно все, осталось немного доделать

**Comment by artemiy312** [comment]
Уже готово:
- отрефакторил docker-compose файлы, чтобы их было удобнее документировать и использовать
- разделил .env файлы и написал скрипт для них
- актуализировал Makefile

Осталось дописать код для ci

**Comment by ivnglkv** [comment]
Может еще автоматом накатывать `shopelectro/shopelectro/fixtures/admin.json`? Чтобы вручную не надо было админский аккаунт создавать.

**Comment by 0pdd** [comment]
@artemiy312 2 puzzles [#303](https://github.com/fidals/shopelectro/issues/303), [#446](https://github.com/fidals/shopelectro/issues/446) are still not solved.
