### ISSUE TITLE
Сайт лежит

### ISSUE THREAD

**Issue by artemiy312** [fidals/shopelectro#270]
<img width="1013" alt="default" src="https://user-images.githubusercontent.com/13870342/37413935-218bab46-27b9-11e8-9042-93bf883ecf7f.png">

https://ci.fidals.com/
https://www.shopelectro.ru/

Похоже, что у нас проблемы с https.

**Comment by artemiy312** [comment]
@duker33 ты вкурсе, что на сервере происходит?

**Comment by ivnglkv** [comment]
Снова лежит

**Comment by ivnglkv** [comment]
Однако поднялся
