### ISSUE TITLE
Похожие товары на 404 странице

### ISSUE THREAD

**Issue by themygit** [fidals/shopelectro#273]
На 404 странице под кнопкой "На главную" выводим  10 рандомных товаров их то же категории, где был удаленный товар. 
С заголовком "Похожие товары"
Две строки по 5 товаров. как на главной http://prntscr.com/ivclw1

**Comment by duker33** [comment]
@ivnglkv , через сутки сниму задачу, если не зарезолвишь

**Comment by ivnglkv** [comment]
@duker33, извиняюсь, был в отпуске, айтишные дела все не трогал, не смотрел
Когда трогал, застопорился на том, что искал, хранятся ли где-то данные об удаленных товарах

**Comment by duker33** [comment]
ждёт, пока потестим CI

**Comment by 0pdd** [comment]
@themygit 2 puzzles [#444](https://github.com/fidals/shopelectro/issues/444), [#445](https://github.com/fidals/shopelectro/issues/445) are still not solved.

**Comment by 0pdd** [comment]
@themygit 2 puzzles [#445](https://github.com/fidals/shopelectro/issues/445), [#470](https://github.com/fidals/shopelectro/issues/470) are still not solved; solved: [#444](https://github.com/fidals/shopelectro/issues/444).

**Comment by 0pdd** [comment]
@themygit 2 puzzles [#445](https://github.com/fidals/shopelectro/issues/445), [#481](https://github.com/fidals/shopelectro/issues/481) are still not solved; solved: [#444](https://github.com/fidals/shopelectro/issues/444), [#470](https://github.com/fidals/shopelectro/issues/470).

**Comment by 0pdd** [comment]
@themygit the puzzle [#481](https://github.com/fidals/shopelectro/issues/481) is still not solved; solved: [#444](https://github.com/fidals/shopelectro/issues/444), [#445](https://github.com/fidals/shopelectro/issues/445), [#470](https://github.com/fidals/shopelectro/issues/470).
