### ISSUE TITLE
Add redirects content

### ISSUE THREAD

**Issue by themygit** [fidals/shopelectro#274]
You can add redirects from this admin page:
http://www.shopelectro.ru/admin/redirects/redirect/

Take login/pass from Duker: https://t.me/duker33

Со страницы:
https://www.shopelectro.ru/catalog/categories/akkumuliatory-270/tags/6f22/
Для этой страницы проставить каноникал на страницу:
https://www.shopelectro.ru/catalog/categories/tiporazmer-6f22/

Со страницы:
https://www.shopelectro.ru/catalog/categories/akkumuliatory-270/tags/aaa/
Проставить каноникал на страницу:
https://www.shopelectro.ru/catalog/categories/tiporazmer-aaa/

Со страницы:
https://www.shopelectro.ru/catalog/categories/akkumuliatory-270/tags/aa/
Проставить каноникал на страницу:
https://www.shopelectro.ru/catalog/categories/tiporazmer-aa/

Со страницы:
https://www.shopelectro.ru/catalog/categories/promyshlennye-3-7-v-li-pol-prizmaticheskie/tags/3-7-v/
Проставить каноникал на страницу:
https://www.shopelectro.ru/catalog/categories/promyshlennye-3-7-v-li-pol-prizmaticheskie/

Со страницы:
https://www.shopelectro.ru/catalog/categories/dlia-noutbukov-ot-seti-220-v/tags/ot-seti-220-v/
Поставить каноникал на страниц:
https://www.shopelectro.ru/catalog/categories/dlia-noutbukov-ot-seti-220-v/

**Comment by duker33** [comment]
тут нужны не канониклы, а просто снести часть категорий и оставить 301-е на них.
Чтобы понять как это делается, нужно раскопать интеграцию с 1С

**Comment by themygit** [comment]
@duker33 го редиректы.

**Comment by duker33** [comment]
this task is not pretty about `Tags content`, but about content

**Comment by duker33** [comment]
tasks reqs is clear already

**Comment by duker33** [comment]
depends on #394

**Comment by duker33** [comment]
loaded content to prod
