### ISSUE TITLE
Не зашли товары из выгрузки

### ISSUE THREAD

**Issue by themygit** [fidals/shopelectro#282]
на se78 через 1с добавили новую группу товаров.
к нам не зашла группа, да и товары тоже. 
https://se78.ru/catalog/slukhovye_apparaty/

**Comment by duker33** [comment]
@themygit , is this task actual?

**Comment by artemiy312** [comment]
@themygit, как я помню, у нас собственная иерархия категорий, поэтому мы не обновляем ее в соответствии с 1С. Товары все зашли, создам категорию и присвою продукты ей.
