### ISSUE TITLE
Меняй формулу ценообразования 

### ISSUE THREAD

**Issue by themygit** [fidals/shopelectro#283]
Когда-то мы искусственно повысили ценник на 1% что бы не казаться аффилиатами у se78
Понизь ценник на 2% (0.99 * real_price). Это даст нам больше шансов в трафике и сео

**Comment by 0pdd** [comment]
@themygit the puzzle [#749](https://github.com/fidals/shopelectro/issues/749) is still not solved.

**Comment by 0pdd** [comment]
@themygit the only puzzle [#749](https://github.com/fidals/shopelectro/issues/749) is solved here.
