### ISSUE TITLE
Change pages content on product page

### ISSUE THREAD

**Issue by themygit** [fidals/shopelectro#287]
2) https://www.shopelectro.ru/catalog/categories/mizinchikovye-aaa-r03-lr03-fr03-286/tags/lr03/
Новый h1 - Батарейки мизинчиковые LR03
Новый title - Батарейки мизинчиковые LR03 (AAA, R03, FR03, 286) – купить в интернет-магазине в СПб оптом
2) https://www.shopelectro.ru/catalog/categories/mizinchikovye-aaa-r03-lr03-fr03-286/tags/fr03/
Новый h1 - Батарейки мизинчиковые FR03
Новый title - Батарейки мизинчиковые FR03 (AAA; R03; LR03; 286) – купить в интернет-магазине в СПб оптом
3) «Батарейки мизинчиковые (AAA; R03; LR03; FR03; 286) r03» — заменить на «Батарейки мизинчиковые R03»
https://www.shopelectro.ru/catalog/categories/mizinchikovye-aaa-r03-lr03-fr03-286/tags/r03/
Новый h1 - Батарейки мизинчиковые R03
Новый title - Батарейки мизинчиковые R03 (AAA; LR03; FR03; 286) – купить в интернет-магазине в СПб оптом

**Comment by artemiy312** [comment]
@themygit готово. Будешь проверять?

**Comment by themygit** [comment]
@artemiy312 закрываем

**Comment by duker33** [comment]
completed
