### ISSUE TITLE
Metrica ecommerce

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#292]
STB too

Integrate yandex and google metrika ecommerce services to our shop.

https://yandex.ru/support/metrika/data/e-commerce.html
https://developers.google.com/analytics/devguides/collection/analyticsjs/ecommerce?hl=ru

**Comment by duker33** [comment]
`hard` because it's big separated feature

**Comment by artemiy312** [comment]
@duker33 what should we do in this issue?

**Comment by duker33** [comment]
@artemiy312 , we should analyze yandex doc, create draft arch and subtasks.
I can take it, if it looks confusing

**Comment by themygit** [comment]
@duker33 you forgot about Google E-Commerce 
https://developers.google.com/analytics/devguides/collection/analyticsjs/ecommerce?hl=ru
Need integrated too. Because we used google analytics for Google merchant center.

**Comment by duker33** [comment]
@themygit , fixed task body

**Comment by artemiy312** [comment]
@themygit ,

Please, make sure that the yandex e-commerce feature and google analytics are turned on
https://yandex.ru/support/metrika/data/e-commerce.html#e-commerce__ecommerce-enable 
https://developers.google.com/analytics/devguides/collection/analyticsjs/?hl=ru

**Comment by duker33** [comment]
@artemiy312 , i'll do it myself, thx for your comment

**Comment by artemiy312** [comment]
@duker33 just in case, I remind you that we use the google tag manager
