### ISSUE TITLE
Fix CI problems. stb2

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#300]
CI does not launch

**Comment by 0pdd** [comment]
@duker33 2 puzzles [#322](https://github.com/fidals/shopelectro/issues/322), [#323](https://github.com/fidals/shopelectro/issues/323) are still not solved.

**Comment by 0pdd** [comment]
@duker33 2 puzzles [#323](https://github.com/fidals/shopelectro/issues/323), [#341](https://github.com/fidals/shopelectro/issues/341) are still not solved; solved: [#322](https://github.com/fidals/shopelectro/issues/322).

**Comment by 0pdd** [comment]
@duker33 the puzzle [#323](https://github.com/fidals/shopelectro/issues/323) is still not solved; solved: [#322](https://github.com/fidals/shopelectro/issues/322), [#341](https://github.com/fidals/shopelectro/issues/341).

**Comment by duker33** [comment]
resloved it in May for astro hours

**Comment by 0pdd** [comment]
@duker33 all 3 puzzles are solved here: [#322](https://github.com/fidals/shopelectro/issues/322), [#323](https://github.com/fidals/shopelectro/issues/323), [#341](https://github.com/fidals/shopelectro/issues/341).
