### ISSUE TITLE
Create category page pagination

### ISSUE THREAD

**Issue by themygit** [fidals/shopelectro#302]
[Google doc contains](https://docs.google.com/document/d/14ZcX5ujkQdIHfZ1tL31Nr1cHnwJ5N037Blsqf5A0jpE/edit#bookmark=id.8ecvb3vcoq6o) requirements for pagination

**Comment by artemiy312** [comment]
Needs info [here](https://docs.google.com/document/d/14ZcX5ujkQdIHfZ1tL31Nr1cHnwJ5N037Blsqf5A0jpE/edit?disco=AAAAB56Apas)

**Comment by duker33** [comment]
@artemiy312 , answered in gDoc. Waiting @themygit for answer

**Comment by duker33** [comment]
@artemiy312 , left comment with total task description. It seems problem resolved

**Comment by 0pdd** [comment]
@themygit 3 puzzles [#338](https://github.com/fidals/shopelectro/issues/338), [#339](https://github.com/fidals/shopelectro/issues/339), [#340](https://github.com/fidals/shopelectro/issues/340) are still not solved.

**Comment by 0pdd** [comment]
@themygit 3 puzzles [#340](https://github.com/fidals/shopelectro/issues/340), [#350](https://github.com/fidals/shopelectro/issues/350), [#351](https://github.com/fidals/shopelectro/issues/351) are still not solved; solved: [#338](https://github.com/fidals/shopelectro/issues/338), [#339](https://github.com/fidals/shopelectro/issues/339).

**Comment by 0pdd** [comment]
@themygit 2 puzzles [#340](https://github.com/fidals/shopelectro/issues/340), [#351](https://github.com/fidals/shopelectro/issues/351) are still not solved; solved: [#338](https://github.com/fidals/shopelectro/issues/338), [#339](https://github.com/fidals/shopelectro/issues/339), [#350](https://github.com/fidals/shopelectro/issues/350).

**Comment by 0pdd** [comment]
@themygit 2 puzzles [#351](https://github.com/fidals/shopelectro/issues/351), [#402](https://github.com/fidals/shopelectro/issues/402) are still not solved; solved: [#338](https://github.com/fidals/shopelectro/issues/338), [#339](https://github.com/fidals/shopelectro/issues/339), [#340](https://github.com/fidals/shopelectro/issues/340), [#350](https://github.com/fidals/shopelectro/issues/350).

**Comment by 0pdd** [comment]
@themygit the puzzle [#351](https://github.com/fidals/shopelectro/issues/351) is still not solved; solved: [#338](https://github.com/fidals/shopelectro/issues/338), [#339](https://github.com/fidals/shopelectro/issues/339), [#340](https://github.com/fidals/shopelectro/issues/340), [#350](https://github.com/fidals/shopelectro/issues/350), [#402](https://github.com/fidals/shopelectro/issues/402).
