### ISSUE TITLE
Makefile:6: Create docs for build system.

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#303]
The puzzle `269-33286093` from #269 has to be resolved:

https://github.com/fidals/shopelectro/blob/64e26c0859107246d10fd2c13e93475021f0473a/docker/Makefile#L6-L6

The puzzle was created by Artemiy on 16-May-18. 

Estimate: 0 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by duker33** [comment]
@artemiy312 , i would like to take this task. Can i?

**Comment by 0pdd** [comment]
@0pdd the puzzle [#446](https://github.com/fidals/shopelectro/issues/446) is still not solved.
