### ISSUE TITLE
Wrong diplayed price precision on product page

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#310]
![image](https://user-images.githubusercontent.com/3526796/40553302-dba3759e-604a-11e8-9253-2e9c070be766.png)

**Comment by artemiy312** [comment]
@duker33 
Should we round it to hundredths (5432.1234 -> 5432.12) or to integers (5432.1234 -> 5432)?

**Comment by duker33** [comment]
@artemiy312 , let's go this way: `(5432.1234 -> 5432.12)`
