### ISSUE TITLE
Broken drone docker-push system. stb2

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#321]
Drone don't watch on master branch. And don't do docker-push after merge in master

UPD: refresh drone code, by the way. No it fully freeze web UI during working

**Comment by duker33** [comment]
problem discussed here:
https://discourse.drone.io/t/how-do-you-trigger-builds-when-a-pr-is-merged/1629/2

**Comment by duker33** [comment]
logs contain nothing suspicious. Just renewed drone itself. Maybe bug will go away

**Comment by artemiy312** [comment]
I am going to enable push hook for drone, which exuecutes build. Seems it will resolve the issue 

Here: https://github.com/fidals/shopelectro/pull/342

**Comment by duker33** [comment]
@artemiy312 , hmm, looks strange. Commented for a little.

and it's not clear why 
```
    when:
      event: push
      branch: master
```
helps to resolve issue

**Comment by artemiy312** [comment]
@duker33 Currently the push hooks is disabled 
<img width="423" alt="default" src="https://user-images.githubusercontent.com/13870342/41358080-45c7f226-6f30-11e8-9151-1e8985948448.png">

When PR will be merged, we may to enable push hook to perform master builds.

`when: ...` branches are needed to filter push hooks for non-master or not targeted to master branches

**Comment by artemiy312** [comment]
@duker33 

It works as I expected
<img width="988" alt="default" src="https://user-images.githubusercontent.com/13870342/41366374-8c924ac6-6f44-11e8-9ba9-7d2197cc7eb5.png">

**Comment by duker33** [comment]
@artemiy312 ,

> Currently the push hooks are disabled

it's strange, i enabled it several days ago

**Comment by duker33** [comment]
it seems this task resolved. But one bug left.
It's here: #347

**Comment by duker33** [comment]
y, it works: https://ci.fidals.com/fidals/shopelectro/167
