### ISSUE TITLE
Choose config vault

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#332]
Removed production by this reasons https://github.com/fidals/shopelectro/pull/329/files#r193071787.
Now let's choose vault to store this config (and env files)

**Comment by duker33** [comment]
As wrote already:
"Simple - on serv and every of us in personal vault. Complex - separated vault or separated cvs repository with configs."

I'm on simple side. We didn't store much more dangerous env files in special vault all this time and had no thoughts and problems with it.
But if we'll create centralized config system of all our using services, we can put this configs there too

**Comment by duker33** [comment]
@artemiy312  suggested using this tool instead of gitolite. It was the suggestion by another question, but it's interesting for this task too.

https://github.com/go-gitea/gitea
https://docs.gitea.io/en-us/comparison/

@artemiy312 , let's make decision for this task to prepare it for work.

**Comment by artemiy312** [comment]
@duker33 
>But if we'll create centralized config system of all our using services, we can put this configs there too.

It sounds nice and simple. Let's stick to this approach

**Comment by duker33** [comment]
won't pay for it
