### ISSUE TITLE
Move update_catalog schedule from celery to cron

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#335]
Create `update_catalog_fully` make recipe and launch it from app's cron.

I think we should do it for several reasons:
- we should launch `price` and `collectstatic` commands regeneration together with update_catalog. And, maybe, nginx's cache clear.
- so, we got complex command for update_catalog. Sometimes we should launch this command with hands from serv. Makefile will avoid code doubling and give us guarantee, that we launch it pretty in the same way, as scheduled task

**Comment by duker33** [comment]
@artemiy312 , what do you think about this task?

**Comment by artemiy312** [comment]
@duker33 
>And, maybe, nginx's cache clear.

why do we need it?

I believe, it will be enough to create composite django command, which we will be used and celery too

**Comment by duker33** [comment]
@artemiy312 , we already have the practice to use Makefile for composite commands.
Admin relies on Makefile as on the full list of available commands.

And we'll create fewer entities in this way: several strings in Makefile vs separated py file

**Comment by artemiy312** [comment]
@duker33 
>we already have the practice to use Makefile for composite commands 

I'm only against the crone, because crone makes pretty the same things, that makes celery for us, so it seems as waste of time. We may implement a receipt for  Makefile instead of a django command if you prefer

>celery beat task for update_catalog works not every two hours

```bash
~/prog/shopelectro/docker# docker-compose -f docker-compose-production.yml logs celery-command-worker | tr -d [:alpha:] | cut -c -30 | uniq
  ---
___.
2018-06-06 14:53
2018-06-06 14:53
2018-06-06 14:53
2018-06-06 14:53
2018-06-06 14:53
2018-06-06 14:53
2018-06-06 16:53
___.
2018-06-06 16:54
2018-06-06 16:54
2018-06-06 16:54
2018-06-06 16:54
2018-06-06 16:54
2018-06-06 16:54
2018-06-06 16:54
2018-06-06 16:56
2018-06-06 16:56
2018-06-06 16:56
2018-06-06 17:00
2018-06-06 17:01
2018-06-06 18:53
___.
2018-06-06 18:54
2018-06-06 18:54
2018-06-06 18:54
2018-06-06 18:54
2018-06-06 18:54
2018-06-06 18:54
2018-06-06 18:54
2018-06-06 18:56
2018-06-06 18:56
2018-06-06 18:56
2018-06-06 19:01
2018-06-06 20:53
___.
2018-06-06 20:54
2018-06-06 20:54
2018-06-06 20:54
2018-06-06 20:54
2018-06-06 20:54
2018-06-06 20:54
2018-06-06 20:54
2018-06-06 20:56
2018-06-06 20:56
2018-06-06 20:56
2018-06-06 21:00
2018-06-06 21:01
2018-06-06 22:53
2018-06-06 22:53
2018-06-06 22:53
2018-06-06 22:53
2018-06-06 22:53
2018-06-06 22:53
2018-06-06 22:53
2018-06-06 22:53
2018-06-06 22:54
2018-06-06 22:54
2018-06-06 22:54
2018-06-06 22:59
2018-06-07 00:53
2018-06-07 00:53
2018-06-07 00:53
2018-06-07 00:53
2018-06-07 00:53
2018-06-07 00:53
2018-06-07 00:53
2018-06-07 00:53
2018-06-07 00:55
2018-06-07 00:55
2018-06-07 00:55
2018-06-07 01:00
2018-06-07 02:53
2018-06-07 02:53
2018-06-07 02:53
2018-06-07 02:53
2018-06-07 02:53
2018-06-07 02:53
2018-06-07 02:53
2018-06-07 02:53
2018-06-07 02:54
2018-06-07 02:55
2018-06-07 02:55
2018-06-07 02:59
2018-06-07 03:00
2018-06-07 04:53
2018-06-07 04:53
2018-06-07 04:53
2018-06-07 04:53
2018-06-07 04:54
2018-06-07 04:54
2018-06-07 04:54
2018-06-07 04:54
2018-06-07 04:55
2018-06-07 04:55
2018-06-07 04:55
2018-06-07 05:00
2018-06-07 06:53
2018-06-07 06:53
2018-06-07 06:53
2018-06-07 06:53
2018-06-07 06:53
2018-06-07 06:53
2018-06-07 06:53
2018-06-07 06:53
2018-06-07 06:55
2018-06-07 06:55
2018-06-07 06:55
2018-06-07 07:02
2018-06-07 08:53
2018-06-07 08:54
2018-06-07 08:54
2018-06-07 08:54
2018-06-07 08:54
2018-06-07 08:54
2018-06-07 08:54
2018-06-07 08:54
2018-06-07 08:56
2018-06-07 08:56
2018-06-07 08:56
2018-06-07 09:01
2018-06-07 10:53
2018-06-07 10:53
2018-06-07 10:53
2018-06-07 10:53
2018-06-07 10:53
2018-06-07 10:53
2018-06-07 10:53
2018-06-07 10:53
2018-06-07 10:55
2018-06-07 10:55
2018-06-07 10:55
2018-06-07 11:00
```

Seems it works as it should

>we must launch collectstatic after update_catalog.

celery executes collectstatic after every update_catalog, so it is not an issue

**Comment by duker33** [comment]
@artemiy312 , 

> I'm only against the crone, because crone makes pretty the same things, that makes celery for us, so it seems as waste of time

both crone and celery are waste of time. But crone is the much wider used then celery.
We already use it for backups by the way.
And we'll launch make command from celery as the command, but not as python expression.
So, let's use Makefile for commands chaining. Choose one crone vs celery.

> Seems it works as it should

It's from prod serv:
```
root@web:~/prog/shopelectro/docker# dcp exec app ls -lt assets/ | grep yandex.yml
total 15168
-rw-r--r-- 1 root root 3396359 Jun  7 07:03 yandex.yml

root@web:~/prog/shopelectro/docker# dcp exec app ls -lt static/ | grep yandex.yml
-rw-r--r-- 1 root root 3396359 Jun  7 07:13 yandex.yml
```

Seems last price was generated about 8 hours ago. It launches commands but shedule, it's true.
But files are generated finally only sometimes. It's problem.


> celery executes collectstatic after every update_catalog, so it is not an issue

y, but ten minutes gap looks from list ahead strange and is not good for our relations with ya.yandex.
Gap = `07:03 - generated, 07:13 - collected as static`

**Comment by artemiy312** [comment]
>But crone is the much wider used then celery.

- We already have solution with celery, which works a long time, so it does not have any sense to re-implement it
- Crone less convenient for us, because we have to implement a docker image with crone and python deps too

> And we'll launch make command from celery as the command, but not as python expression.

I thought we were going to run in the recipe python expression like:
`dcp run --rm app python manage.py shell "from shopelectro.tasks import update_catalog as u; u()"`

>Seems last price was generated about 8 hours ago.

This is bug of docker-compose file descriptions. There is no `volumes_from: app`, that provides delivery to the `app` container
<img width="740" alt="default" src="https://user-images.githubusercontent.com/13870342/41112364-6229de82-6a87-11e8-8369-43ccd1897570.png">

```bash
~/prog/shopelectro/docker# docker-compose -f docker-compose-production.yml exec celery-command-worker date
Thu Jun  7 16:35:51 UTC 2018
~/prog/shopelectro/docker# docker-compose -f docker-compose-production.yml exec celery-command-worker ls -lah static/yandex.yml
-rw-r--r-- 1 root root 3.3M Jun  7 15:00 static/yandex.yml
```

**Comment by duker33** [comment]
@artemiy312 , 

> We already have solution with celery, which works a long time, so it does not have any sense to reinvent this solution

it didn't work, as we just invented :) But long, it's true.
Moreover, now we have new circumstances: we create Makefile and should avoid code doubling.

> I thought we were going to run in the recipe python expression like:

we already decided to use Makefile to avoid code doubling. So, it'll look like `subproccess.call('make prices')`

> Crone less convenient for us, because we have to implement a docker image with crone and python deps too

every linux has crone. If we choose crone, all we need is to mount one file to `app` service with one string indside. And then rm ~30 python strings from `tasks.py`.

> There is no volumes_from: app, that provides delivery to the app container

it's not good to increase dependencies count. In this way celery worker will be dependent from app.

So, decide celery vs crone.

And for affirmation: i suggest to launch `make prices` as periodic task to avoid code doubling. This avoiding will save admin's hours

**Comment by artemiy312** [comment]
@duker33 

>Moreover, now we have new circumstances: we create Makefile and should avoid code doubling.

>we already decided to use Makefile to avoid code doubling. So, it'll look like subproccess.call('make prices')

We are able to avoid code doubling with such Makefile's receipt:
```Makefile
generate-prices:
    @dcp run --rm app python manage.py shell -c "from shopelectro.tasks import update_catalog as u; u()"
    # also we may call `u` blocking `u()` or non-blocking `u.delay()`
```

>every linux has crone.

Are you propose to use a host cron or a dockerized cron in this case?

>it's not good to increase dependencies count. In this way celery worker will be dependent from app.

It is the docker-compose issue, because it is the single way to organize works with volumes (also in the latest docker-compose version, the issue was [resolved](https://docs.docker.com/compose/compose-file/#volume-configuration-reference))

**Comment by duker33** [comment]
@artemiy312 , 

> @dcp run --rm app python manage.py shell -c "from shopelectro.tasks import update_catalog as u; u()"

Y, it solves the problem of painful doubling. It looks more complex then `@dcp run --rm app python manage.py update_catalog` + cron.
But seems to me as smth vitable. We can choose this way instead of cron, if you insist.

> Are you propose to use a host cron or a dockerized cron in this case?

i propose dockerized cron, of course. In ideal case host machine should know only about set of docker-compose config's and Makefile.
We already choosed this way in `backup-data` service.

The last problem here is to choose appropriate service where to put cron config. Every of your services already has cron, because every linux has it.
I think, `app` is the most good one.

> It is the docker-compose issue

anyway, it brings complexity of volumes binding between containers. It doesn't matter how docker implements this complexity.
Crone avoids this complexity by simple and decades-using concept.

**Comment by artemiy312** [comment]
@duker33 
> I think, app is the most good one.

`app` is not good  place for it. We should stick to "one process per container". Each container should have only one concern, so we should create separate service such as "catalog-cron" and this state of the art will be the same, that we already has with celery workers.

> Crone avoids this complexity by simple and decades-using concept.

In dockerized case is not avoid the complexity of volumes mounting 

I still believe, that the best solution will be:
- leave the celery
- fix docker-compose-production.yml
- add new receipt for update_catalog execution.

**Comment by duker33** [comment]
@artemiy312 , i'll just repair fastly in the separated task. And leave this one here :)
