### ISSUE TITLE
base.py:162-164: Drop `dj_database_url` dependency. This...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#337]
The puzzle `142-764900e7` from #142 has to be resolved:

https://github.com/fidals/shopelectro/blob/6d75d963c9ec9066eda72be2284502da4444bb7f/shopelectro/settings/base.py#L162-L164

The puzzle was created by duker on 08-Jun-18. 

Estimate: 0 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
@liza-andreeva done it
