### ISSUE TITLE
tests_views.py:58: Divide the CatalogPage test class into...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#338]
The puzzle `302-31c4df63` from #302 has to be resolved:

https://github.com/fidals/shopelectro/blob/96e14747c3d7da9dd7db50f01bbb987147e4e2cb/shopelectro/tests/tests_views.py#L58-L58

The puzzle was created by Artemiy on 08-Jun-18. 

Estimate: 0 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by 0pdd** [comment]
The puzzle `302-31c4df63` has disappeared from the source code, that's why I closed this issue. //cc @artemiyds2 @duker33

**Comment by duker33** [comment]
double of #350
