### ISSUE TITLE
tests_views.py:204-207: Implement test case for...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#339]
The puzzle `302-ab23fc9d` from #302 has to be resolved:

https://github.com/fidals/shopelectro/blob/96e14747c3d7da9dd7db50f01bbb987147e4e2cb/shopelectro/tests/tests_views.py#L204-L207

The puzzle was created by Artemiy on 08-Jun-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by 0pdd** [comment]
The puzzle `302-ab23fc9d` has disappeared from the source code, that's why I closed this issue. //cc @artemiyds2 @duker33

**Comment by duker33** [comment]
>  If step=24 and page number=2 and total products quantity is 40, then products quantity is 40. 

@artemiy312 , pagination should work in another manner. Page 2 should not contain products from page 1.
In this case page2 should contain `40-24 = 16` products. Let's put `16` instead of `40` for the second case of tests. And fix code to make this requirement working

**Comment by liza-andreeva** [comment]
В итоге нужно проверить 48 и 96?
Если да, то в https://github.com/fidals/shopelectro/pull/364 уже такая логика.

**Comment by duker33** [comment]
@liza-andreeva , @artemiy312 , let's more discussion to #351
