### ISSUE TITLE
category_products.html:5: Implement pagination buttons...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#340]
The puzzle `302-bdb9bbef` from #302 has to be resolved:

https://github.com/fidals/shopelectro/blob/96e14747c3d7da9dd7db50f01bbb987147e4e2cb/templates/catalog/category_products.html#L5-L5

The puzzle was created by Artemiy on 08-Jun-18. 

Estimate: 60 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by artemiy312** [comment]
@duker33 , should hidden buttons either reload (by link) or update (by ajax) the state of a category page?

**Comment by duker33** [comment]
@artemiy312 , page full updating will be enough. But choose the most convenient way for realization.

The main requirement here is to load right products set by direct link `/my_prod/?page_num=3`
