### ISSUE TITLE
Do `gulp build` on image side

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#345]
Currently, we have problems with gulp build on client side. See #344 for details.
Moreover, building static on container site is more good practice

**Comment by 0pdd** [comment]
@duker33 the puzzle [#352](https://github.com/fidals/shopelectro/issues/352) is still not solved.

**Comment by 0pdd** [comment]
@duker33 2 puzzles [#448](https://github.com/fidals/shopelectro/issues/448), [#449](https://github.com/fidals/shopelectro/issues/449) are still not solved; solved: [#352](https://github.com/fidals/shopelectro/issues/352).

**Comment by 0pdd** [comment]
@duker33 5 puzzles [#448](https://github.com/fidals/shopelectro/issues/448), [#449](https://github.com/fidals/shopelectro/issues/449), [#457](https://github.com/fidals/shopelectro/issues/457), [#458](https://github.com/fidals/shopelectro/issues/458), [#459](https://github.com/fidals/shopelectro/issues/459) are still not solved; solved: [#352](https://github.com/fidals/shopelectro/issues/352).

**Comment by 0pdd** [comment]
@duker33 4 puzzles [#448](https://github.com/fidals/shopelectro/issues/448), [#458](https://github.com/fidals/shopelectro/issues/458), [#459](https://github.com/fidals/shopelectro/issues/459), [#464](https://github.com/fidals/shopelectro/issues/464) are still not solved; solved: [#352](https://github.com/fidals/shopelectro/issues/352), [#449](https://github.com/fidals/shopelectro/issues/449), [#457](https://github.com/fidals/shopelectro/issues/457).

**Comment by 0pdd** [comment]
@duker33 2 puzzles [#458](https://github.com/fidals/shopelectro/issues/458), [#459](https://github.com/fidals/shopelectro/issues/459) are still not solved; solved: [#352](https://github.com/fidals/shopelectro/issues/352), [#448](https://github.com/fidals/shopelectro/issues/448), [#449](https://github.com/fidals/shopelectro/issues/449), [#457](https://github.com/fidals/shopelectro/issues/457), [#464](https://github.com/fidals/shopelectro/issues/464).
