### ISSUE TITLE
.drone.yml:16-17: Use ready image for drone npm step....

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#352]
The puzzle `345-fd64d13a` from #345 has to be resolved:

https://github.com/fidals/shopelectro/blob/7a0860ec73f09921c59980111869af0d2319ad80/.drone.yml#L16-L17

The puzzle was created by duker33 on 15-Jun-18. 

Estimate: 60 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by artemiy312** [comment]
Seems it is required for #416

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#448](https://github.com/fidals/shopelectro/issues/448), [#449](https://github.com/fidals/shopelectro/issues/449) are still not solved.

**Comment by 0pdd** [comment]
@0pdd 5 puzzles [#448](https://github.com/fidals/shopelectro/issues/448), [#449](https://github.com/fidals/shopelectro/issues/449), [#457](https://github.com/fidals/shopelectro/issues/457), [#458](https://github.com/fidals/shopelectro/issues/458), [#459](https://github.com/fidals/shopelectro/issues/459) are still not solved.

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#448](https://github.com/fidals/shopelectro/issues/448), [#458](https://github.com/fidals/shopelectro/issues/458), [#459](https://github.com/fidals/shopelectro/issues/459), [#464](https://github.com/fidals/shopelectro/issues/464) are still not solved; solved: [#449](https://github.com/fidals/shopelectro/issues/449), [#457](https://github.com/fidals/shopelectro/issues/457).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#458](https://github.com/fidals/shopelectro/issues/458), [#459](https://github.com/fidals/shopelectro/issues/459) are still not solved; solved: [#448](https://github.com/fidals/shopelectro/issues/448), [#449](https://github.com/fidals/shopelectro/issues/449), [#457](https://github.com/fidals/shopelectro/issues/457), [#464](https://github.com/fidals/shopelectro/issues/464).
