### ISSUE TITLE
Redirects mech broken

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#360]
Prod db contains these urls in redirects list.
But redirect from first to second is not working

1. https://www.shopelectro.ru/catalog/categories/akkumuliatory-270/tags/6f22/
2. https://www.shopelectro.ru/catalog/categories/tiporazmer-6f22/

**Comment by duker33** [comment]
django standard redirects mech triggers only for not found urls
https://github.com/django/django/blob/master/django/contrib/redirects/middleware.py#L26

I'll try to move this app to refarm-site and customize it's behaviour for our needs

**Comment by duker33** [comment]
we'll resolve this problem at https://github.com/fidals/refarm-site/issues/140

Just created the test. It specifies problem

**Comment by 0pdd** [comment]
@duker33 3 puzzles [#405](https://github.com/fidals/shopelectro/issues/405), [#406](https://github.com/fidals/shopelectro/issues/406), [#407](https://github.com/fidals/shopelectro/issues/407) are still not solved.

**Comment by 0pdd** [comment]
@duker33 the puzzle [#407](https://github.com/fidals/shopelectro/issues/407) is still not solved; solved: [#405](https://github.com/fidals/shopelectro/issues/405), [#406](https://github.com/fidals/shopelectro/issues/406).

**Comment by 0pdd** [comment]
@duker33 all 3 puzzles are solved here: [#405](https://github.com/fidals/shopelectro/issues/405), [#406](https://github.com/fidals/shopelectro/issues/406), [#407](https://github.com/fidals/shopelectro/issues/407).
