### ISSUE TITLE
Catalog prices autoupdate error

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#365]
Command don't do periodically price generation

**Comment by artemiy312** [comment]
@duker33 appending `volumes_from: app` to [celery-command-worker:](https://github.com/fidals/shopelectro/blob/master/docker/docker-compose-production.yml#L98) will fix this, so why did you estimate the issue in 1 hour?

**Comment by duker33** [comment]
@artemiy312 , maybe this mech was broken some time ago.
I'll turn it to `1 hour` again, if `volumes_from: app` will not enough.

`30 mins`, because i should check with hands if it works on prod

**Comment by themygit** [comment]
@duker33 Наверное лучше отпишусь в этой задаче. Ибо как я понимаю это 1 команда. Умерла генерация прайс листа екселевского - он пустой. не генерица сайтмеп  в формате xml и нас отключили из маркета за разницу в market.yml  и ценами на сайте.

**Comment by artemiy312** [comment]
@duker33 If you do not mind, I am going to take this issue. Ok?

**Comment by artemiy312** [comment]
seems `volumes_from` fix the issue. I updated the  celery worker 
```bash
artemiy$ docker-compose -f docker-compose-production.yml exec app date
Thu Jul 19 02:16:20 UTC 2018
artemiy$ curl -s -H'Cache-Control: no-cache' http://0.0.0.0:8010/static/yandex.yml | head -n 3
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE yml_catalog SYSTEM "shops.dtd">
<yml_catalog date="2018-07-19 02:15">
```

**Comment by duker33** [comment]
it's hot task, so 1 hour
