### ISSUE TITLE
Selenium tests random timeouts catched

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#371]
Selenium started to return timeouts for random tests

https://ci.fidals.com/fidals/shopelectro/209/8
https://ci.fidals.com/fidals/shopelectro/211/8
https://ci.fidals.com/fidals/shopelectro/212/8

**Comment by duker33** [comment]
i'll try to increase timeouts

**Comment by duker33** [comment]
seems it works

**Comment by 0pdd** [comment]
@duker33 the puzzle [#373](https://github.com/fidals/shopelectro/issues/373) is still not solved.

**Comment by 0pdd** [comment]
@duker33 the only puzzle [#373](https://github.com/fidals/shopelectro/issues/373) is solved here.
