### ISSUE TITLE
Products re-linking as on stb

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#388]
We already have this functinality on stb.

[Reqs from seo guys](https://docs.google.com/document/d/14ZcX5ujkQdIHfZ1tL31Nr1cHnwJ5N037Blsqf5A0jpE/edit?ts=5b13c914#).

Screen [is from this page](http://www.stroyprombeton.ru/gbi/products/638/)

![image](https://user-images.githubusercontent.com/3526796/41849042-4833b5de-7888-11e8-817d-3b18f98ef147.png)

**Comment by duker33** [comment]
i take this task, because it's about requirements clarifying

**Comment by 0pdd** [comment]
@duker33 2 puzzles [#505](https://github.com/fidals/shopelectro/issues/505), [#506](https://github.com/fidals/shopelectro/issues/506) are still not solved.

**Comment by 0pdd** [comment]
@duker33 2 puzzles [#506](https://github.com/fidals/shopelectro/issues/506), [#529](https://github.com/fidals/shopelectro/issues/529) are still not solved; solved: [#505](https://github.com/fidals/shopelectro/issues/505).

**Comment by 0pdd** [comment]
@duker33 the puzzle [#529](https://github.com/fidals/shopelectro/issues/529) is still not solved; solved: [#505](https://github.com/fidals/shopelectro/issues/505), [#506](https://github.com/fidals/shopelectro/issues/506).
