### ISSUE TITLE
Save image files from test_db. stb2

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#389]
Now files no saving leads us to 404 errors in tests.
See #359 to find how errors look like

**Comment by duker33** [comment]
i'll do the same func on stb

**Comment by 0pdd** [comment]
@duker33 the puzzle [#404](https://github.com/fidals/shopelectro/issues/404) is still not solved.

**Comment by 0pdd** [comment]
@duker33 the only puzzle [#404](https://github.com/fidals/shopelectro/issues/404) is solved here.
