### ISSUE TITLE
Check containers building and starting. stb2

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#396]
Now we have the problem. We don't check if `docker build` and/or `docker up` of new containers was broken with code changes

**Comment by 0pdd** [comment]
@duker33 the puzzle [#408](https://github.com/fidals/shopelectro/issues/408) is still not solved.

**Comment by 0pdd** [comment]
@duker33 the puzzle [#517](https://github.com/fidals/shopelectro/issues/517) is still not solved; solved: [#408](https://github.com/fidals/shopelectro/issues/408).

**Comment by 0pdd** [comment]
@duker33 the puzzle [#587](https://github.com/fidals/shopelectro/issues/587) is still not solved; solved: [#408](https://github.com/fidals/shopelectro/issues/408), [#517](https://github.com/fidals/shopelectro/issues/517), [#534](https://github.com/fidals/shopelectro/issues/534).

**Comment by 0pdd** [comment]
@duker33 all 4 puzzles are solved here: [#408](https://github.com/fidals/shopelectro/issues/408), [#517](https://github.com/fidals/shopelectro/issues/517), [#534](https://github.com/fidals/shopelectro/issues/534), [#587](https://github.com/fidals/shopelectro/issues/587).
