### ISSUE TITLE
Tags content problems

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#398]
Comment `#1` from content:

> Запятые в 7 шаблоне исправил.
> На этих страницах: https://www.shopelectro.ru/catalog/categories/akkumuliatory-270/tags/4-v/
https://www.shopelectro.ru/catalog/categories/akkumuliatory-270/tags/12-v/ что-то не так с подтягиванием тэгов с бэкэнда. Я временно изменил вывод тэгов в заголовке - сейчас отображается с названием группы тэгов. Если посмотрите именно на эти 2 страницы, там выводятся "номинальное напряжение" и "питание", в то время как на всех других только "номинальное напряжение"

Comment `#2` from content:
> Да, обнаружил эту проблему для 3х тэгов: "4 В", "12 В" и "Li-Po".
> Я не специалист по Джанго, поэтому просто мои наблюдения. Так понимаю, что все тэги собраны по группам ("Номинальное напряжение", "Производитель" и т.д.). Я временно делал в шаблоне, чтобы вместе с тэгом выводилось название группы, к которой он принадлежит. Оказалось, что если отметить галочкой на фронте "4 В" и "12 В", то они забираются сразу из двух групп - "Номинальное напряжение" и "Питание", в то время как остальные ("3.7 В", "6 В" и т.д.) только из одной - "Номинальное напряжение". Для "Li-Po" подробно не смотрел, но, полагаю, что происходит то же самое - тэг забирается сразу из двух групп.

Full list of links with problems:
https://www.shopelectro.ru/catalog/categories/akkumuliatory-270/tags/4-v/
https://www.shopelectro.ru/catalog/categories/akkumuliatory-270/tags/12-v/
https://www.shopelectro.ru/catalog/categories/akkumuliatory-270/tags/li-ro/
https://www.shopelectro.ru/catalog/categories/promyshlennye-3-7-v-li-pol-prizmaticheskie/tags/li-ro/
https://www.shopelectro.ru/catalog/categories/dlia-radioupravliaemykh-modelei-i-igrushek/tags/li-ro/
https://www.shopelectro.ru/catalog/categories/svintsovo-kislotnye-akkumuliatory/tags/12-v/
https://www.shopelectro.ru/catalog/categories/svintsovo-kislotnye-akkumuliatory/tags/4-v/

**Comment by duker33** [comment]
we have the same tag for several tag groups. Which is ok, but breaks some `tag_titles` usecases

```
In [1]: from shopelectro.models import Tag

In [2]: Tag.objects.filter(name='4 В')
Out[2]: <QuerySet [<Tag: 4 В>, <Tag: 4 В>]>

In [3]: tags = _

In [4]: [t.group.name for t in tags]
Out[4]: ['Номинальное напряжение', 'Питание']
```

**Comment by duker33** [comment]
code for page template should look like this

```
{% if tags|length_is:'1' %}
  in if
  {% for tag in tags %}
    in for
    {% if tag.name == '4 В' and tag.group.name == 'Напряжение' %}
    my good text
    {% endif %}
  {% endfor %}
{% endif %}
```
but backend responses with two tags `4 В`. It's bug, i'll write test

**Comment by 0pdd** [comment]
@duker33 the puzzle [#522](https://github.com/fidals/shopelectro/issues/522) is still not solved.

**Comment by 0pdd** [comment]
@duker33 the puzzle [#535](https://github.com/fidals/shopelectro/issues/535) is still not solved; solved: [#522](https://github.com/fidals/shopelectro/issues/522).

**Comment by 0pdd** [comment]
@duker33 all 2 puzzles are solved here: [#522](https://github.com/fidals/shopelectro/issues/522), [#535](https://github.com/fidals/shopelectro/issues/535).
