### ISSUE TITLE
test_db.py:70-72: Set db name in `test_db` command. stb2...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#404]
The puzzle `389-3679238e` from #389 has to be resolved:

https://github.com/fidals/shopelectro/blob/f9866fd7277181919e30fd17e6366d6225277a32/shopelectro/management/commands/test_db.py#L70-L72

The puzzle was created by duker33 on 06-Jul-18. 

Estimate: 60 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
refarm too

**Comment by duker33** [comment]
that's how django test runner do this:

```
# django.db.backends.base.creation.BaseDatabaseCreation#create_test_db

        settings.DATABASES[self.connection.alias]["NAME"] = test_database_name
        self.connection.settings_dict["NAME"] = test_database_name
```
