### ISSUE TITLE
починить sitemap.xml

### ISSUE THREAD

**Issue by themygit** [fidals/shopelectro#410]
Сейчас он выдает 500 ошибку

**Comment by duker33** [comment]
@artemiy312 , i don't agree with `1h`. I suggest `30 min`

**Comment by artemiy312** [comment]
@duker33 This problem required research on a production machine and a non-trivial decision to fix it, so I suggest to leave this estimation. If you still does not agree with it, then let me know and I will update it.

**Comment by duker33** [comment]
agreed with `1 hour`. Wrote additional comment in direct chat, because it's about devops
