### ISSUE TITLE
Create robots page in fixtures. stb2

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#417]

**Comment by artemiy312** [comment]
@duker33 We already have robots.txt in fixutres

**Comment by duker33** [comment]
@artemiy312 , checked, it exists.

But we have the different problem.
http://127.0.0.1:8010/robots.txt returns it:
```
DoesNotExist at /robots.txt/
CustomPage matching query does not exist.
```

**Comment by duker33** [comment]
@artemiy312 , i found and proved problem, so i want my `15 mins` :)

**Comment by artemiy312** [comment]
@duker33 Let's create the same test for STB too
