### ISSUE TITLE
Меняй макс кол-во символов в h1

### ISSUE THREAD

**Issue by themygit** [fidals/shopelectro#435]
СЕО отдел просит увеличить макс количество символов в H1 - до уровня дискрипшена. 
Так как у нас есть проблемы с дублями свойств в заголовках, они хотят формировать их с помощью тегов.  Типа так получается ок.  Но с текущем ограничением - не пропускает фильтр.

**Comment by themygit** [comment]
Эта штука нам мешает жить и портит красоту 
https://www.shopelectro.ru/catalog/categories/chasovye-batareiki-serebriano-tsinkovye/tags/serebriano-tsinkovyi/
Можно побыстрее ?

**Comment by duker33** [comment]
seems it's about db schema. That's why `30 mins`
