### ISSUE TITLE
CI.md:25-26: Try to rm --no-cache build flags from drone...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#446]
The puzzle `303-7eff8043` from #303 has to be resolved:

https://github.com/fidals/shopelectro/blob/380d159b411e97c655c666f44fe876715b9f1834/CI.md#L25-L26

The puzzle was created by duker33 on 25-Jul-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
flags leaved without any fight
