### ISSUE TITLE
Potential unique error on adding deactivated product via 1C

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#467]
This PR may provide issue https://github.com/fidals/shopelectro/pull/443

Issue possible scenario:
**step 1** - rm product
- manager removes product `Battery #1` from 1C
- catalog `update_catalog` command launches 1C import with the schedule
- product `Battery #1` becomes deactivated

**step 2** - add product back
- manager adds product `Battery #1` again
- catalog `update_catalog` launches 1C import with the schedule
- `update_db` command fails because of unique product name constraint

**Comment by artemiy312** [comment]
@duker33 Seems, such error can not be raised. Should we try to merge a new and deactivated product at the creation stage?

**Comment by duker33** [comment]
@artemiy312 , we should not merge, i think. No merging strategy is more simple and explicit
