### ISSUE TITLE
Ya.Metric aim wrong behaviour

### ISSUE THREAD

**Issue by themygit** [fidals/shopelectro#471]
В яндекс метрике есть цель купить общая - отрабатывает при покупке через корзину или в 1 клик. В метрику приходят далеко не все заказы

http://prntscr.com/ke1788 - почта

http://prntscr.com/ke17t6 - метрика

**Comment by duker33** [comment]
seems it's doubling https://github.com/fidals/shopelectro/issues/439
I'll clarify it during today's release

**Comment by duker33** [comment]
i'll check it at 07.08 JS code was fixed by Artemiy
