### ISSUE TITLE
Tracker errors on production

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#475]
Two points at this task: GaTracker and YaMetric.Ecommerce

- `GaTracker failed to load. Traceback: TypeError: c is not a function` in main.js. Main page

~~Three errors about ecommerce. All's at main js:~~ it because of [this
](https://github.com/fidals/shopelectro/blob/master/front/js/shared/yandex.es6#L28)- ecommerce:addTransaction, {id: "DummyId"}
- ecommerce:send undefined, 
- ecommerce:addItem, {id: "438", name: "Батарейка renata R364 (SR 621SW) SR 60, 1.55 В", quantity: "1"}

**Comment by artemiy312** [comment]
Seems, gulp obfuscate the some important block of code.
From main.min.js:
```js
  try {
    c('require', 'ecommerce')
  } catch (e) {
    var c = console.error;
    console.error('GaTracker failed to load. Traceback: ' + e)
  }
```
