### ISSUE TITLE
yandex.es6:87-88: Enable and test COPY_PHONE and...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#493]
The puzzle `473-2be6ecfc` from #473 has to be resolved:

https://github.com/fidals/shopelectro/blob/f7dc2793dc5c7eddb2e68a68368337d77ba3139e/front/js/shared/yandex.es6#L87-L88

The puzzle was created by duker33 on 08-Aug-18. 

Estimate: 60 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
@themygit , do we need `COPY_PHONE` and `COPY_MAIL` ya.metrika aims?

I'll repeat this question in direct messages

**Comment by duker33** [comment]
PO answered that we are don't needed in this aims. So, just rm it's code

**Comment by 0pdd** [comment]
@0pdd the puzzle [#515](https://github.com/fidals/shopelectro/issues/515) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#515](https://github.com/fidals/shopelectro/issues/515) is solved here.
