### ISSUE TITLE
tests_selenium.py:805-806: Fix yandex.kassa payment type...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#496]
The puzzle `489-209a5aa0` from #489 has to be resolved:

https://github.com/fidals/shopelectro/blob/abd13f0d6364eecdada5c2cfaaa37ee8c79c6429/shopelectro/tests/tests_selenium.py#L805-L806

The puzzle was created by duker33 on 09-Aug-18. 

Estimate: 60 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
PO and Business told about situations when orders are not sent.
PO assumes, that it's about only ya.kassa orders.

So, business and PO reports about this bug too
