### ISSUE TITLE
tests_selenium.py:654: Move `payment_type` to dict or...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#497]
The puzzle `473-9a69e4d0` from #473 has to be resolved:

https://github.com/fidals/shopelectro/blob/abd13f0d6364eecdada5c2cfaaa37ee8c79c6429/shopelectro/tests/tests_selenium.py#L654-L654

The puzzle was created by duker33 on 09-Aug-18. 

Estimate: 15 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by artemiy312** [comment]
I going to implement `selenium.pages.OrderPage.select_payment_type` method within this task

**Comment by 0pdd** [comment]
The puzzle `473-9a69e4d0` has disappeared from the source code, that's why I closed this issue. //cc @artemiyds2 @duker33
