### ISSUE TITLE
Bug in e-commerce report

### ISSUE THREAD

**Issue by themygit** [fidals/shopelectro#504]
Популярные категории и бренды - пустой. по идее должны передаваться просмотры товаров и категорий. 
Содержимое заказов - Все падает в 1 id и без цен. Нужно делить товары по заказам и передавать цены в отчет. https://metrika.yandex.ru/stat/orders_products?period=week&id=20644114 
в отчет "Заказанные товары" передаются имена и id - наверное нужно только имена ?

**Comment by artemiy312** [comment]
- [ ] категории и бренды товаров
- [ ] id заказа после покупки
- [ ] цены товаров заказа

**Comment by artemiy312** [comment]
@themygit  , 
>в отчет "Заказанные товары" передаются имена и id - наверное нужно только имена ?

Убрать id?

**Comment by themygit** [comment]
@artemiy312 судя по графикам, отчет Товары в корзине тоже не работает. Должны передаваться товары и их количество, которые добавляют в корзину

**Comment by themygit** [comment]
@artemiy312 когда сможешь закрыть ?

**Comment by artemiy312** [comment]
@themygit ждал ревью, скоро закрою

**Comment by 0pdd** [comment]
@themygit 3 puzzles [#524](https://github.com/fidals/shopelectro/issues/524), [#525](https://github.com/fidals/shopelectro/issues/525), [#526](https://github.com/fidals/shopelectro/issues/526) are still not solved.

**Comment by 0pdd** [comment]
@themygit 2 puzzles [#525](https://github.com/fidals/shopelectro/issues/525), [#526](https://github.com/fidals/shopelectro/issues/526) are still not solved; solved: [#524](https://github.com/fidals/shopelectro/issues/524).

**Comment by 0pdd** [comment]
@themygit 3 puzzles [#525](https://github.com/fidals/shopelectro/issues/525), [#526](https://github.com/fidals/shopelectro/issues/526), [#537](https://github.com/fidals/shopelectro/issues/537) are still not solved; solved: [#524](https://github.com/fidals/shopelectro/issues/524).

**Comment by 0pdd** [comment]
@themygit 2 puzzles [#525](https://github.com/fidals/shopelectro/issues/525), [#537](https://github.com/fidals/shopelectro/issues/537) are still not solved; solved: [#524](https://github.com/fidals/shopelectro/issues/524), [#526](https://github.com/fidals/shopelectro/issues/526).

**Comment by 0pdd** [comment]
@themygit the puzzle [#537](https://github.com/fidals/shopelectro/issues/537) is still not solved; solved: [#524](https://github.com/fidals/shopelectro/issues/524), [#525](https://github.com/fidals/shopelectro/issues/525), [#526](https://github.com/fidals/shopelectro/issues/526).
