### ISSUE TITLE
tests_selenium.py:698: Resurrect test `test_empty_cart`

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#515]
The puzzle `493-6db30696` from #493 has to be resolved:

https://github.com/fidals/shopelectro/blob/efa708a89ca52e2497dbe2a86f4c3b71ad102e4d/shopelectro/tests/tests_selenium.py#L698-L698

The puzzle was created by duker33 on 15-Aug-18. 

Estimate: 15 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by artemiy312** [comment]
Close in favor of #610
