### ISSUE TITLE
tests_views.py:190-193: Fix doubled tags issue....

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#522]
The puzzle `398-023fcade` from #398 has to be resolved:

https://github.com/fidals/shopelectro/blob/6806692e83bba09f669baf022ed379e56d7e0b4d/shopelectro/tests/tests_views.py#L190-L193

The puzzle was created by duker33 on 17-Aug-18. 

Estimate: 60 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
thought about the decisions some time. There are two ones:
- create tag urls with tag group name before
- create hashes only for repeated tag names

The second one is the most productive, i think. It's short and simple.
I'll describe it with test and pdd subtask

**Comment by duker33** [comment]
implemented the suggested in pr decision. So, we'll resolve problem without additional pdd issue

**Comment by 0pdd** [comment]
@0pdd the puzzle [#535](https://github.com/fidals/shopelectro/issues/535) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#535](https://github.com/fidals/shopelectro/issues/535) is solved here.
