### ISSUE TITLE
tracking.es6:35: Send info about product's brand to YA...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#525]
The puzzle `504-f7f52310` from #504 has to be resolved:

https://github.com/fidals/shopelectro/blob/4e607fb856842b43192511b1b4eaff19d2052b9a/front/js/shared/tracking.es6#L35-L35

The puzzle was created by Artemiy on 17-Aug-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by artemiy312** [comment]
I am going to implement it in single PR and seems it will take a little bit more time

**Comment by 0pdd** [comment]
@0pdd the puzzle [#537](https://github.com/fidals/shopelectro/issues/537) is still not solved.
