### ISSUE TITLE
category_products.html:42: Rename `productId` like format...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#526]
The puzzle `504-93dfa99a` from #504 has to be resolved:

https://github.com/fidals/shopelectro/blob/4e607fb856842b43192511b1b4eaff19d2052b9a/templates/catalog/category_products.html#L42-L42

The puzzle was created by Artemiy on 17-Aug-18. 

Estimate: 15 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by artemiy312** [comment]
I ran into the failure of the tests, so I am going to increase the estimate
