### ISSUE TITLE
product.html:121-122: Create slider for product's...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#529]
The puzzle `505-f0844092` from #505 has to be resolved:

https://github.com/fidals/shopelectro/blob/48aae8460c30738d595234a6885c6dc9e0bc22db/templates/catalog/product.html#L121-L122

The puzzle was created by Artemiy on 17-Aug-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
slider is not very hot task. And i move out of myself front tasks for a while

**Comment by duker33** [comment]
it's front task, but should be implemented.
I take it with `x2` price

**Comment by duker33** [comment]
it's front task, but should be implemented.
I take it with `x2` price

**Comment by duker33** [comment]
it's siblings list. Now it takes two rows. We should merge it to one row with slider
![image](https://user-images.githubusercontent.com/3526796/50412595-ae1f4400-0819-11e9-9ace-489a5207bf33.png)

**Comment by duker33** [comment]
discussing with PO if we should drop this task.
It looks like not good UX in my opinion

**Comment by duker33** [comment]
PO rejected this issue
