### ISSUE TITLE
Удали товары из фида

### ISSUE THREAD

**Issue by themygit** [fidals/shopelectro#533]
Из фида gm.yml (для мерчант центра) удаляй товары дешевле 200 рублей 
Условие работает только для этого фида.

**Comment by 0pdd** [comment]
@themygit the puzzle [#547](https://github.com/fidals/shopelectro/issues/547) is still not solved.

**Comment by 0pdd** [comment]
@themygit the only puzzle [#547](https://github.com/fidals/shopelectro/issues/547) is solved here.
