### ISSUE TITLE
tests_models.py:85-90: Try to implement...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#537]
The puzzle `525-5d17d280` from #525 has to be resolved:

https://github.com/fidals/shopelectro/blob/64939d2fe050fd9c4cbd110be802a9a0444ca5aa/shopelectro/tests/tests_models.py#L85-L90

The puzzle was created by Artemiy on 22-Aug-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by artemiy312** [comment]
I'd prefer to leave `Tag.objects.get_brands()`, because a brand is `Tag` object

**Comment by duker33** [comment]
@artemiy312 , maybe then Product.objects.get_brands() ?
Props:
- we don't needed method arg `products` in client code
- we don't needed in Tag class in client code: `Tag.objects.get_brands(products.get_brands())` -> `products.get_brands()`

**Comment by artemiy312** [comment]
@duker33 

`products.get_brands()` maybe looks more convenient, but will work ineffective as i showed through [test](https://github.com/fidals/shopelectro/blob/64939d2fe050fd9c4cbd110be802a9a0444ca5aa/shopelectro/tests/tests_models.py#L85-L90)
