### ISSUE TITLE
Change imported objects prefix styles

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#542]
Task origins [from this comment](https://github.com/fidals/shopelectro/pull/541#discussion_r212349277).

Rename `caTag` to CaTag or RfTag. Do this renaming for all over the code.

We have no either convention or linter rule about it.
But we have practiced for all over the code. Example from the same module:
`from ecommerce.models import Order as ecOrder`

**Comment by duker33** [comment]
Lowercase first letter seems good for me. Because it's module name. And modules are always not capitalized.

But rf seems as good idea for me.

So, i suggest this: `caTag` -> `rfTag`

**Comment by artemiy312** [comment]
@duker33 a class name [should be ](https://www.python.org/dev/peps/pep-0008/#class-names) started by uppercase letter

**Comment by duker33** [comment]
@artemiy312 , `rfTag` is variable name, if we want to be strict there :)
But "class *MyClass*" is class name.
We have pycodetyle linter on, and he says nothing about it.

But if we'll throw away this purity, i think RfTag is bad UX decision. When i see capitalized `Rf`, i'll think about refarm project as about last option. I can think about roofed tag or smth.
Lowercase `rf` says, that it's prefix, but not sensitive part of the class name

**Comment by duker33** [comment]
@artemiy312 , let's close this discussion

**Comment by artemiy312** [comment]
@duker33 
rfTag is not variable name. An imported class is still a class, so we should name it respectively. Show it:
```python
In [10]: from logging import StreamHandler

In [11]: from logging import StreamHandler as sh

In [12]: type(StreamHandler)
Out[12]: type

In [13]: type(sh)
Out[13]: type

In [14]: StreamHandler is sh
Out[14]: True
```

>i think RfTag is bad UX decision

If we import `RfSomething` from `refarm_site`, then it is definitely not `RoofedSomething`, isn't it?
And we are not talking about UX, but about code style for a class name, that has certain rules

I leave the right to choose for you :)

**Comment by duker33** [comment]
i think we'll just import parent modules and use them as prefixes
