### ISSUE TITLE
Return E305 pycodestyle rule

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#548]
currently coala's config contains this code string:
`pycodestyle_ignore = E305,W503`

But it's pep8's rule, as Guide says here: https://github.com/PyCQA/pycodestyle/issues/400

**Comment by duker33** [comment]
@artemiy312 , what do you think about this issue?

**Comment by artemiy312** [comment]
@duker33 let's remove these codes from pycodestyle_ignore to stick to pep8
