### ISSUE TITLE
tests_views.py:253-254: Create test(s) for numbered...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#555]
The puzzle `539-97439133` from #539 has to be resolved:

https://github.com/fidals/shopelectro/blob/f6ab9f062e9740d0f7114da7aa742855f30f5fbc/shopelectro/tests/tests_views.py#L253-L254

The puzzle was created by Artemiy on 29-Aug-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
it's required for Tags
