### ISSUE TITLE
catalog.py:29: Move PaginatorLinks to refarm-site.

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#556]
The puzzle `539-e6f6dde5` from #539 has to be resolved:

https://github.com/fidals/shopelectro/blob/f6ab9f062e9740d0f7114da7aa742855f30f5fbc/shopelectro/views/catalog.py#L29-L29

The puzzle was created by Artemiy on 29-Aug-18. 

Estimate: 60 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
it's required for STB tags

**Comment by artemiy312** [comment]
I am going to redesign pagination classes and create a context class for these, so i will increase an estimate
