### ISSUE TITLE
Не пришел заказ на почту

### ISSUE THREAD

**Issue by themygit** [fidals/shopelectro#561]
https://www.shopelectro.ru/admin/shopelectro/order/7833/change/
Говоряn, что этот заказ не заехал на почту. 
по поиску я его не нашел 
менеджеры написали, что его номер - 13833

**Comment by artemiy312** [comment]
заказ попал в екомерс отчет метрики

**Comment by themygit** [comment]
Тогда проблемы с почтой ? @duker33 делал какое-то логгирование. Под эту
проблему
пн, 3 сент. 2018 г. в 22:17, Artemiy <notifications@github.com>:

**Comment by artemiy312** [comment]
судя по логам яндексовский aviso успешно выполнился в 2018-08-31T11:57:24.009+03:00 и
письма отправились магазину и покупателю:

```python
se-celery-mail-worker    | [2018-08-31 11:57:24,297: INFO/MainProcess] Received task: ecommerce.tasks.send_mail[52067e71-b4a3-49f3-a776-ec6e8eee47e8]
se-celery-mail-worker    | [2018-08-31 11:57:24,315: INFO/MainProcess] Received task: ecommerce.tasks.send_mail[4ccff1a6-4044-4b95-bcc2-68933d230026]
se-celery-mail-worker    | [2018-08-31 11:57:25,647: INFO/ForkPoolWorker-4] Task ecommerce.tasks.send_mail[52067e71-b4a3-49f3-a776-ec6e8eee47e8] succeeded in 1.342135155107826s: None
se-celery-mail-worker    | [2018-08-31 11:57:25,707: INFO/ForkPoolWorker-5] Task ecommerce.tasks.send_mail[4ccff1a6-4044-4b95-bcc2-68933d230026] succeeded in 1.3861108953133225s: None
```

**Comment by themygit** [comment]
Клиенту засылают. А нам нет
пн, 3 сент. 2018 г. в 23:24, Artemiy <notifications@github.com>:

**Comment by artemiy312** [comment]
I enabled [acks_late](http://docs.celeryproject.org/en/latest/reference/celery.app.task.html#celery.app.task.Task.acks_late) for `send_mail` task to reach reliability

**Comment by themygit** [comment]
@artemiy312 удалось понять в чем проблема ?

**Comment by artemiy312** [comment]
@themygit, судя по логам мы отправили письмо. Ошибки не было, как и в прошлый раз

**Comment by duker33** [comment]
@themygit , посмотрел в `info-back`. Действительно не долетел заказ. Какие-то проблемы с самой почтой, видимо.
Более поздние заказы на Я.Кассу норм отправляли письма.
Так что закрываю задачу
