### ISSUE TITLE
context.py:113-117: Move context realization to pure to...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#567]
The puzzle `550-c08f412e` from #550 has to be resolved:

https://github.com/fidals/shopelectro/blob/9399dd6b93c990e55b854080e7a4d5ee48a95f5e/shopelectro/context.py#L113-L117

The puzzle was created by duker33 on 07-Sep-18. 

Estimate: 120 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
connected with #566

**Comment by duker33** [comment]
this task blocks huge set of views cleanup tasks. So, `1` tag

**Comment by 0pdd** [comment]
The puzzle `550-c08f412e` has disappeared from the source code, that's why I closed this issue. //cc @artemiyds2 @duker33

**Comment by duker33** [comment]
it's not closed truly. It's pdd code just moved to refarm repo

**Comment by duker33** [comment]
actual task is here:
https://github.com/fidals/refarm-site/issues/183
