### ISSUE TITLE
баг в формуле прайса xls

### ISSUE THREAD

**Issue by themygit** [fidals/shopelectro#574]
[Прайс неправильный.xlsx](https://github.com/fidals/shopelectro/files/2379518/default.xlsx)
Менеджеры отписали, что прайс неверно посчитал итоговую сумму. 
Текст ниже:
Мне вчера клиент прислал прайс с заказом, но когда я его заказ вбила в 1С у меня разошлись суммы. В прайсе товара на 26000, по факту заказ на 36000. Начала искать ошибку, сбоку в прайсе вывела формулу, где формула посчитала сумму заказа на 36000.

**Comment by themygit** [comment]
Какую инфу еще уточнить ?

**Comment by artemiy312** [comment]
@duker33 I will take the issue if you do not mind
