### ISSUE TITLE
context.py:261-262: Move `TaggedCategory.get_tags` to...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#579]
The puzzle `550-79bb63d1` from #550 has to be resolved:

https://github.com/fidals/shopelectro/blob/b17502325196e8ad5ff6b18fbf964584ffb62da9/shopelectro/context.py#L261-L262

The puzzle was created by duker33 on 16-Sep-18. 

Estimate: 15 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by 0pdd** [comment]
The puzzle `550-79bb63d1` has disappeared from the source code, that's why I closed this issue. //cc @artemiyds2 @duker33

**Comment by duker33** [comment]
it's not closed truly. It's pdd code just moved to refarm repo

**Comment by duker33** [comment]
duplicates https://github.com/fidals/refarm-site/issues/185
