### ISSUE TITLE
Не приходят оплаченные заказы на почту

### ISSUE THREAD

**Issue by themygit** [fidals/shopelectro#585]
https://prnt.sc/kwtnid от 19 числа. на почту не приходил

**Comment by duker33** [comment]
we have fake ids, so `8062 == 14062`

**Comment by duker33** [comment]
Artemiy improved and monitored logs at https://github.com/fidals/shopelectro/issues/561
We send mails in all cases. So, the problem is in some mail side.

Currently i have no idea how we can debug it. But i'll try in some way

**Comment by themygit** [comment]
Не дошел заказ 8095
и в почте 3 заказа, 4 потеряли, а метрика показывает 1 продажу

**Comment by themygit** [comment]
не дошел 8103
@duker33 есть идеи почему ?
моя теория с шаблонами и некорректным заполнением - лажа ?

**Comment by duker33** [comment]
it's hard task, that requires devops skills. So, `x2`

**Comment by duker33** [comment]
we can test email sending with vanilla django mech:
https://docs.djangoproject.com/en/2.1/topics/testing/tools/#email-services

**Comment by duker33** [comment]
we had problems with this two orders:
https://www.shopelectro.ru/admin/shopelectro/order/7833/change/?_changelist_filters=p%3D6%26q%3D
https://www.shopelectro.ru/admin/shopelectro/order/8103/change/?_changelist_filters=p%3D4%26q%3D

Both this cases went from Ya.Kassa. I'll try to cover them with tests in this task and close it

**Comment by duker33** [comment]
found it in selenium section.
Task is resolved by https://github.com/fidals/shopelectro/pull/602
