### ISSUE TITLE
Измени расчет дохода в {yandex,google}.ecommerce 

### ISSUE THREAD

**Issue by themygit** [fidals/shopelectro#589]
есть два отчета
отчет по цели купить общая https://metrika.yandex.ru/stat/new?goal=14331608&metric=ym%3As%3Agoal%3Cgoal_id%3Ereaches&sort=-ym%3As%3Agoal%3Cgoal_id%3Ereaches&chart_type=line&period=week&table=visits&title=%D0%9F%D0%BE%D0%BA%D1%83%D0%BF%D0%BA%D0%B0&id=20644114&stateHash=5b9fafb3a76af6f1f5f22d98
отчет екоммерца по заказам 
https://metrika.yandex.ru/stat/purchase?period=week&id=20644114&stateHash=5b9fa61af33d8ae0c408b0e3
в первом 47 во втором 59 посетителей, которые что-то купили
почему ? и кто прав ? 
Может туда заходят не оплаченные заказы через кассу ? 
и хотел узнать по строке доход, в екоммерц отчете. В ней из стоимости товара вычитывается себестоимость, как и я просил ? или как ?

**Comment by artemiy312** [comment]
@themygit 

Мы отправляем данные о заказах, когда юзер попадает на /shop/order-success/, дальше яшка самостоятельна формирует отчеты.

Не видел такого требования. Сейчас доход формируется из суммы заказа

**Comment by themygit** [comment]
@artemiy312 тогда нужно доделать это мы забираем из 1c

**Comment by 0pdd** [comment]
@themygit 2 puzzles [#598](https://github.com/fidals/shopelectro/issues/598), [#599](https://github.com/fidals/shopelectro/issues/599) are still not solved.
