### ISSUE TITLE
tests_models.py:30: Create test for Order.set_positions

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#598]
The puzzle `589-d53d6ac5` from #589 has to be resolved: 

https://github.com/fidals/shopelectro/blob/d540802063d91f7171e87f5d7b0be2cc5dd164e7/shopelectro/tests/tests_models.py#L30-L30

The puzzle was created by Artemiy on 05-Oct-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
i suppose we aren't
