### ISSUE TITLE
Long serv response

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#603]
Every page responses with timeout of ~3s.
Sometimes category and product pages return 502 error.

Checked this pages: Main, Category, Product

**Comment by duker33** [comment]
on local machine with fixtures category page eat responses with ~1.6 sec.
DB queries part takes only 100 ms.

So, we have ~1.5 sec inside app

**Comment by duker33** [comment]
seems it's about templates. View logic with disabled templates stuff responses in 300-400 ms.

And version `1.5.0` renders category page with 1.5 sec too.

Maybe we had caching enabled, but it disabled now

**Comment by duker33** [comment]
seems it's problems with cache. Checked with debug toolbar on prod: we have 0 cache hits now.
So, i'll see on our caching mech

**Comment by duker33** [comment]
blocked by #606

**Comment by duker33** [comment]
now release cache mech enabling and test if this issue is resolved

**Comment by duker33** [comment]
released it. Problem is still there

**Comment by duker33** [comment]
i'll fully reproduce prods SE structure on local and start debugging

**Comment by duker33** [comment]
reproduced it on local. Gunicorn worker fails with timeout. I'm debugging it

**Comment by duker33** [comment]
appended lru_cache for this problem place. Now releasing it

**Comment by 0pdd** [comment]
@duker33 the puzzle [#617](https://github.com/fidals/shopelectro/issues/617) is still not solved.

**Comment by 0pdd** [comment]
@duker33 3 puzzles [#617](https://github.com/fidals/shopelectro/issues/617), [#624](https://github.com/fidals/shopelectro/issues/624), [#625](https://github.com/fidals/shopelectro/issues/625) are still not solved.

**Comment by 0pdd** [comment]
@duker33 the puzzle [#625](https://github.com/fidals/shopelectro/issues/625) is still not solved; solved: [#617](https://github.com/fidals/shopelectro/issues/617), [#624](https://github.com/fidals/shopelectro/issues/624).
