### ISSUE TITLE
models.py:228-236: Fix model.Manager bad inheritance Now...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#612]
The puzzle `rf169-b846c0cd` from #rf169 has to be resolved: 

https://github.com/fidals/shopelectro/blob/8a1096905808fc61125187376c4099c2ab101ec7/shopelectro/models.py#L228-L236

The puzzle was created by duker33 on 22-Oct-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by 0pdd** [comment]
The puzzle `rf169-b846c0cd` has disappeared from the source code, that's why I closed this issue. //cc @artemiyds2 @duker33

**Comment by duker33** [comment]
Connected with https://github.com/fidals/stroyprombeton/issues/327

**Comment by duker33** [comment]
it's hard problem, i suppose. But i can't refuse it

**Comment by duker33** [comment]
seems `mptt` produces this bug. Trying to install the last version and check if it'll be fixed

**Comment by duker33** [comment]
asked question on SO.
So, i'll wait for one or several days now
https://stackoverflow.com/questions/53498308/django-mptts-mpttmodel-inheritance-issue

**Comment by artemiy312** [comment]
You should try to remove `models.Manager.from_queryset` and inheritance directly from managers.

```python
import mptt
from django.db import models


class MyTreeQuerySet(mptt.querysets.TreeQuerySet):
    def t(self):
        return self.all()
class MyTreeManager(mptt.managers.TreeManager):
    def t(self):
        return self.get_queryset().t()

class TreeModel(mptt.models.MPTTModel):
    class Meta:
        app_label = 'myapp'
    objects = MyTreeManager()

print(type(TreeModel.objects.t()))
```

**Comment by duker33** [comment]
y, looks we should go this way. I'll try it

**Comment by duker33** [comment]
the problem is in managers. Graded example above

**Comment by duker33** [comment]
found solution: we should use `mptt.managers.TreeManager.from_queryset` instead of `dj_models.Manager.from_queryset`.
MPTTModel.__new__ has some magic with TreeManager mixing into active managers list. I didn't dig in.

```
In [28]: dj_models.Manager.from_queryset(models.ExcludedModelTPageQuerySet).__mro__                                                                                          
Out[28]: 
(django.db.models.manager.ManagerFromExcludedModelTPageQuerySet,
 django.db.models.manager.Manager,
 django.db.models.manager.BaseManagerFromQuerySet,
 django.db.models.manager.BaseManager,
 object)

In [29]: mptt.managers.TreeManager.from_queryset(models.ExcludedModelTPageQuerySet).__mro__                                                                                  
Out[29]: 
(django.db.models.manager.TreeManagerFromExcludedModelTPageQuerySet,
 mptt.managers.TreeManager,
 django.db.models.manager.ManagerFromTreeQuerySet,
 django.db.models.manager.Manager,
 django.db.models.manager.BaseManagerFromQuerySet,
 django.db.models.manager.BaseManager,
 object)
```

**Comment by duker33** [comment]
this task fixes https://github.com/fidals/refarm-site/issues/199 too

**Comment by 0pdd** [comment]
@0pdd the puzzle [#662](https://github.com/fidals/shopelectro/issues/662) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#662](https://github.com/fidals/shopelectro/issues/662) is solved here.
