### ISSUE TITLE
docker-compose.yml:21-24: Resurrect postgres waiting This...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#617]
The puzzle `603-bf36ae82` from #603 has to be resolved: 

https://github.com/fidals/shopelectro/blob/1ea961c17a6337817c1385072e2af8b594c1e242/docker/docker-compose.yml#L21-L24

The puzzle was created by duker33 on 24-Oct-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by artemiy312** [comment]
Duplicate of #594
