### ISSUE TITLE
Create redirect from redundant tag 

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#626]
https://www.shopelectro.ru/catalog/categories/akkumuliatory-270/tags/li-ro/
should do 301 redirect to
https://www.shopelectro.ru/catalog/categories/akkumuliatory-270/tags/li-ro_hbced/

**Comment by duker33** [comment]
it can be non-trivial task

**Comment by artemiy312** [comment]
It seems we can create this redirect from admin page, if so, it will be a rather trivial
