### ISSUE TITLE
Добавь разделы в выпадающее меню.

### ISSUE THREAD

**Issue by themygit** [fidals/shopelectro#634]
Добавь эти разделы в выпадающее меню 

http://prntscr.com/liogas

https://www.shopelectro.ru/catalog/categories/pirotekhnika/
https://www.shopelectro.ru/catalog/categories/iskusstvennye-iolki/

**Comment by themygit** [comment]
@artemiy312 @duker33 Мне срочненько

**Comment by artemiy312** [comment]
@themygit готово

<img width="518" alt="default" src="https://user-images.githubusercontent.com/13870342/48557934-08fb7c80-e8f9-11e8-8ce2-aaebb49649c0.png">
