### ISSUE TITLE
Divide execution of fast and slow tests.

### ISSUE THREAD

**Issue by artemiy312** [fidals/shopelectro#639]
Stop a build process if fast tests fail. This will decrease tests execution time

We already have implemented this in STB.
See this: https://github.com/fidals/stroyprombeton/issues/348 and https://github.com/fidals/stroyprombeton/issues/358

**Comment by 0pdd** [comment]
@artemiy312 the puzzle [#647](https://github.com/fidals/shopelectro/issues/647) is still not solved.
