### ISSUE TITLE
Добавляй блок на главную 

### ISSUE THREAD

**Issue by themygit** [fidals/shopelectro#643]
Дублируем блок "Большой выбор аккумуляторов, батареек и блоков питания" и выводим перед ним:

Заголовок “Новогодние товары: гирлянды, украшения и фейерверки”

1 ссылка:
Название: Новогодние гирлянды <b>от NNN* руб.</b>
https://www.shopelectro.ru/catalog/categories/novogodnie-girliandy-207/
https://www.shopelectro.ru/media/cache/c3/95/c3959207881bad593025f0c816f684ad.png

2 ссылка:
Название: Лазерные проекторы <b>от NNN* руб.</b>
https://www.shopelectro.ru/catalog/categories/novogodnie-lazernye-proektory-209/
https://www.shopelectro.ru/media/cache/94/a1/94a112b12d4f69d1a23d773f7531422a.png

3 ссылка:
Название: Новогодние фейерверки и салюты <b>от NNN* руб.</b>
https://www.shopelectro.ru/catalog/categories/pirotekhnika/
https://www.shopelectro.ru/media/cache/09/8e/098e803979561596242e97a22eb7f8de.png

**Comment by duker33** [comment]
work with image styles

**Comment by themygit** [comment]
@duker33 ты забыл о заголовках. 
если написано не явно, то их должно быть два 
Новогодние товары: гирлянды, украшения и фейерверки
Большой выбор аккумуляторов, батареек и блоков питания
