### ISSUE TITLE
Stale previews on category page under load_more

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#645]
At #641 fixed similar issue. But it was about product page.

https://www.shopelectro.ru/catalog/categories/akkumuliatory-270/

**Comment by 0pdd** [comment]
@duker33 2 puzzles [#654](https://github.com/fidals/shopelectro/issues/654), [#655](https://github.com/fidals/shopelectro/issues/655) are still not solved.

**Comment by 0pdd** [comment]
@duker33 the puzzle [#654](https://github.com/fidals/shopelectro/issues/654) is still not solved; solved: [#655](https://github.com/fidals/shopelectro/issues/655).
