### ISSUE TITLE
Debug wrong seotext in template

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#648]
It leads to 502 error now

https://github.com/fidals/stroyprombeton/issues/334#issuecomment-442795845

**Comment by duker33** [comment]
prod works now

**Comment by duker33** [comment]
now test kills the whole app container in 50% of launches.
So, i skip it

**Comment by duker33** [comment]
Caught this traceback as PageTemplate.render() value during one of test launches.
But can't reproduce it again:
https://gist.github.com/duker33/909ea2751ed171f50521d6cc48e32834

**Comment by duker33** [comment]
met this error on the prod again. The error is about Cyrillic symbols

**Comment by duker33** [comment]
met this error two days ago. Now all's good. We'll continue working in related task

**Comment by 0pdd** [comment]
@duker33 the only puzzle [#651](https://github.com/fidals/shopelectro/issues/651) is solved here.
