### ISSUE TITLE
500 ошибка в админке

### ISSUE THREAD

**Issue by themygit** [fidals/shopelectro#656]
https://www.shopelectro.ru/admin/shopelectro/productpage/?has_category=no

**Comment by duker33** [comment]
found this lines in failed admin traceback from prod:
```
se-python                |   File "/usr/app/src/shopelectro/admin.py", line 163, in model_id
se-python                |     return obj.model.vendor_code
```

Right now we have 65 not active product pages with no binded products. Seems it's because of them.

I suppose, that they appeared from `update_db` command. We can't test it now with TDD

**Comment by duker33** [comment]
Analyzed bad pages set. They are old, but already bad copies of existing and active products:
```
In [1]:  pp = ProductPage.objects.filter(shopelectro_product=None).first()

In [2]: p = Product.objects.get(name=pp.name)

In [3]: pp.id, p.page.id
Out[3]: (8344, 8379)

In [4]: pp.is_active, p.page.is_active
Out[4]: (False, True)

In [5]: pp.date_published, p.page.date_published
Out[6]: (datetime.date(2018, 7, 31), datetime.date(2018, 7, 31))
```

I'll just rm all such bad pages from prod db. But the problem is to define where this pages came from.
I'll write test that update product with commands update_db mech. I'll try to catch bad pages copies creating

**Comment by duker33** [comment]
found pages consistency issue in `update_db` commands. Reflected it in related PR.
But this issue seems not fully related to our problem

**Comment by duker33** [comment]
Removed problem pages from prod.
Problem with link solved, as we waited
```
In [1]: bad_pages = ProductPage.objects.filter(shopelectro_product=None)

In [2]: bad_pages.count()
Out[2]: 65

In [3]: bad_pages.delete()
Out[3]: (65, {'images.Image': 0, 'shopelectro.ProductPage': 65})
```

**Comment by 0pdd** [comment]
@themygit the puzzle [#669](https://github.com/fidals/shopelectro/issues/669) is still not solved.

**Comment by 0pdd** [comment]
@themygit the only puzzle [#669](https://github.com/fidals/shopelectro/issues/669) is solved here.
