### ISSUE TITLE
Create healthcheck

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#682]
Something like very simple selenium tests on production.
They should be launched every day for example.
And show current status via telegram channel/bot/github_badge or smth

**Comment by 0pdd** [comment]
@duker33 3 puzzles [#690](https://github.com/fidals/shopelectro/issues/690), [#691](https://github.com/fidals/shopelectro/issues/691), [#692](https://github.com/fidals/shopelectro/issues/692) are still not solved.

**Comment by duker33** [comment]
`Selenium pages` feature (a block cleanup tasks) was introduced at the related PR

**Comment by 0pdd** [comment]
@duker33 3 puzzles [#691](https://github.com/fidals/shopelectro/issues/691), [#692](https://github.com/fidals/shopelectro/issues/692), [#704](https://github.com/fidals/shopelectro/issues/704) are still not solved; solved: [#690](https://github.com/fidals/shopelectro/issues/690).

**Comment by 0pdd** [comment]
@duker33 2 puzzles [#691](https://github.com/fidals/shopelectro/issues/691), [#692](https://github.com/fidals/shopelectro/issues/692) are still not solved; solved: [#690](https://github.com/fidals/shopelectro/issues/690), [#704](https://github.com/fidals/shopelectro/issues/704), [#712](https://github.com/fidals/shopelectro/issues/712).

**Comment by 0pdd** [comment]
@duker33 3 puzzles [#691](https://github.com/fidals/shopelectro/issues/691), [#692](https://github.com/fidals/shopelectro/issues/692), [#809](https://github.com/fidals/shopelectro/issues/809) are still not solved; solved: [#690](https://github.com/fidals/shopelectro/issues/690), [#704](https://github.com/fidals/shopelectro/issues/704), [#712](https://github.com/fidals/shopelectro/issues/712).
