### ISSUE TITLE
Integrate new Context classes

### ISSUE THREAD

**Issue by artemiy312** [fidals/shopelectro#683]
You can get these classes from https://github.com/fidals/refarm-site/issues/183

**Comment by artemiy312** [comment]
We will be capable to do it after https://github.com/fidals/refarm-site/pull/238

**Comment by 0pdd** [comment]
@artemiy312 4 puzzles [#698](https://github.com/fidals/shopelectro/issues/698), [#699](https://github.com/fidals/shopelectro/issues/699), [#700](https://github.com/fidals/shopelectro/issues/700), [#701](https://github.com/fidals/shopelectro/issues/701) are still not solved.

**Comment by 0pdd** [comment]
@artemiy312 3 puzzles [#699](https://github.com/fidals/shopelectro/issues/699), [#700](https://github.com/fidals/shopelectro/issues/700), [#701](https://github.com/fidals/shopelectro/issues/701) are still not solved; solved: [#698](https://github.com/fidals/shopelectro/issues/698).

**Comment by 0pdd** [comment]
@artemiy312 2 puzzles [#699](https://github.com/fidals/shopelectro/issues/699), [#700](https://github.com/fidals/shopelectro/issues/700) are still not solved; solved: [#698](https://github.com/fidals/shopelectro/issues/698), [#701](https://github.com/fidals/shopelectro/issues/701).

**Comment by 0pdd** [comment]
@artemiy312 the puzzle [#700](https://github.com/fidals/shopelectro/issues/700) is still not solved; solved: [#698](https://github.com/fidals/shopelectro/issues/698), [#699](https://github.com/fidals/shopelectro/issues/699), [#701](https://github.com/fidals/shopelectro/issues/701).

**Comment by 0pdd** [comment]
@artemiy312 the puzzle [#775](https://github.com/fidals/shopelectro/issues/775) is still not solved; solved: [#698](https://github.com/fidals/shopelectro/issues/698), [#699](https://github.com/fidals/shopelectro/issues/699), [#700](https://github.com/fidals/shopelectro/issues/700), [#701](https://github.com/fidals/shopelectro/issues/701).
