### ISSUE TITLE
Grade to Django 1.11. stb2

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#685]
Current 1.10 contains minor security issues

**Comment by artemiy312** [comment]
Let's bump it to `1.11.17`. This version [should be used](https://docs.djangoproject.com/en/2.1/faq/install/#what-python-version-can-i-use-with-django) for python 3.7

**Comment by artemiy312** [comment]
I have faced with these issues:
- `liveserver` option removed from `django==1.11`'s `manage.py`
- some form fields changed their structure, without mentions this in release notes
