### ISSUE TITLE
Broken aims on gAnalitics

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#706]
This is text from seo guys:

---

Прошу обратить внимание на то что перестали считаться «ассоциированные конверсии» и снизилось достижение цели «Купил» хотя в Яндекс.Метрике я не вижу снижения кол-ва конверсий ни по цели «Купить общая» ни по цели «Купил» или «Купил в один клик» (по некоторым целям фиксируется рост). Есть возможность проверить правильность работы целей в Google Analytics?

**Comment by duker33** [comment]
@artemiy312 , i would like to take this issue if you did not start it.
PO is in hurry with it.
Would i?

**Comment by duker33** [comment]
@artemiy312 , last time u like to take front tasks. Maybe you want to take this gAnalitics.

Increased price because of task burning

**Comment by artemiy312** [comment]
As i understood it is about google eCommerce, so we should check google tag manager first, because it should load google `analytics.js` script with `ga` function, that is always missed:  
```javascript
GaTracker failed to load. Traceback: TypeError: ga is not a function main.min.cc77fb2c73ea.js:1:7278
```

**Comment by artemiy312** [comment]
@duker33 Is it about google eCommerce? I am asking because I don't see any code related to google goals in the project, but the issue's description looks like about goals

**Comment by duker33** [comment]
@artemiy312 , y, seems we never had such goals at google analytics
![image](https://user-images.githubusercontent.com/3526796/53824542-39892400-3f85-11e9-93aa-7d4a24c7e94c.png)
