### ISSUE TITLE
Add canonicals to category page

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#718]
For example this two pages contains no canonicals:
- https://www.shopelectro.ru/catalog/categories/akkumuliatory-270/tags/li-ro_hbced/?page=2
- ~https://www.shopelectro.ru/catalog/categories/akkumuliatory-270/?page=2~ checked - it contains canonical

**Comment by duker33** [comment]
found this tests with interesting commets:
```
def test_paginated_tags_page_has_no_canonical_meta_tag(self):
	"""
	Test CategoryTagsPage with canonical tags.

	CategoryTagsPage with pagination (and sorting) options
	should not contain canonical meta tag.
	"""

def test_paginated_tags_page_has_no_canonical_meta_tag(self):
	"""
	Test CategoryTagsPage with canonical tags.

	CategoryTagsPage with pagination (and sorting) options
	should not contain canonical meta tag.
	"""
```

i'll ask PO if we should create canonicals for tags

**Comment by duker33** [comment]
PO answered, that every `?page=N` should have canonical on it's non-paginated version

**Comment by 0pdd** [comment]
@duker33 the puzzle [#722](https://github.com/fidals/shopelectro/issues/722) is still not solved.
