### ISSUE TITLE
Wrap request args with some RequestData class

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#723]
Now we have problem with request args. We calc this args in different not relevant places and pass them as one huge ungrouped args set. See code example below.

Incapsulate request args processing and passing with some universal `RequestData` class.

```
# it's part of shopelectro.views.catalog.CategoryPage.get_context_data method

        contexts = get_catalog_context(
            request=self.request,
            page=self.object,
            category=self.object.model,
            raw_tags=self.kwargs.get('tags'),
            page_number=int(self.request.GET.get('page', 1)),
            per_page=int(self.request.GET.get(
                'step', get_products_count(self.request),
            )),
            sorting_index=sorting_index,
        )
```

**Comment by duker33** [comment]
This feature is inspired by #699, but is separated one, as i understood after some prototyping.
I'll implement them together with one PR

**Comment by 0pdd** [comment]
@duker33 the puzzle [#731](https://github.com/fidals/shopelectro/issues/731) is still not solved.
