### ISSUE TITLE
tests_views.py:499: Fix...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#749]
The puzzle `283-ce00cf9b` from #283 has to be resolved: 

https://github.com/fidals/shopelectro/blob/de8c9ea043df884931ec76fd5d963b1f0b27f899/shopelectro/tests/tests_views.py#L499-L499

The puzzle was created by @artemiy312 on 23-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by artemiy312** [comment]
It was false positive issue
