### ISSUE TITLE
Unstable Ya.Metrica

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#754]
- as for 27.02 shop had 11 real orders on mail and 8 ones counted with metric

Seems metric is unstable.

Possible solutions:
- add sentry monitoring for js code

![image](https://user-images.githubusercontent.com/3526796/53557448-02ff7380-3b57-11e9-8bab-db78468b4b88.png)

**Comment by artemiy312** [comment]
@duker33 What were these metrics? eCommerce or goal counter?

**Comment by duker33** [comment]
@artemiy312 , it's about goal counter

**Comment by artemiy312** [comment]
@duker33 , the goal counter could be easily blocked by adblock, so i just integrate sentry for js

**Comment by duker33** [comment]
@artemiy312 , y, it's good decision for this task
