### ISSUE TITLE
Broken google ecommerce integration

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#759]
https://github.com/fidals/shopelectro/issues/706

20 feb 2019 we broke google analytics. Resurrect it.
Check if tests for ecommerce are working.

(under mediaprime acc)
https://analytics.google.com/analytics/web/?authuser=0#/report/conversions-ecommerce-overview/a42239144w71929328p74216659/_u.date00=20190201&_u.date01=20190305/

![image](https://user-images.githubusercontent.com/3526796/53860725-fa91b780-3ff2-11e9-87e2-f6c267ac0aaf.png)

**Comment by duker33** [comment]
@artemiy312 , this task is requirements clarifying of #706. So, it's for you :)

**Comment by 0pdd** [comment]
@duker33 2 puzzles [#761](https://github.com/fidals/shopelectro/issues/761), [#762](https://github.com/fidals/shopelectro/issues/762) are still not solved.

**Comment by artemiy312** [comment]
It [works](https://analytics.google.com/analytics/web/?authuser=1#/report/conversions-ecommerce-transaction/a42239144w71929328p74216659/_u.date00=20190301&_u.date01=20190312/), so i am going to continue with #761 #762

**Comment by 0pdd** [comment]
@duker33 4 puzzles [#761](https://github.com/fidals/shopelectro/issues/761), [#762](https://github.com/fidals/shopelectro/issues/762), [#771](https://github.com/fidals/shopelectro/issues/771), [#772](https://github.com/fidals/shopelectro/issues/772) are still not solved.

**Comment by 0pdd** [comment]
@duker33 3 puzzles [#761](https://github.com/fidals/shopelectro/issues/761), [#762](https://github.com/fidals/shopelectro/issues/762), [#785](https://github.com/fidals/shopelectro/issues/785) are still not solved; solved: [#771](https://github.com/fidals/shopelectro/issues/771), [#772](https://github.com/fidals/shopelectro/issues/772).

**Comment by 0pdd** [comment]
@duker33 3 puzzles [#762](https://github.com/fidals/shopelectro/issues/762), [#785](https://github.com/fidals/shopelectro/issues/785), [#795](https://github.com/fidals/shopelectro/issues/795) are still not solved; solved: [#761](https://github.com/fidals/shopelectro/issues/761), [#771](https://github.com/fidals/shopelectro/issues/771), [#772](https://github.com/fidals/shopelectro/issues/772).

**Comment by 0pdd** [comment]
@duker33 3 puzzles [#762](https://github.com/fidals/shopelectro/issues/762), [#795](https://github.com/fidals/shopelectro/issues/795), [#799](https://github.com/fidals/shopelectro/issues/799) are still not solved; solved: [#761](https://github.com/fidals/shopelectro/issues/761), [#771](https://github.com/fidals/shopelectro/issues/771), [#772](https://github.com/fidals/shopelectro/issues/772), [#785](https://github.com/fidals/shopelectro/issues/785).

**Comment by 0pdd** [comment]
@duker33 4 puzzles [#762](https://github.com/fidals/shopelectro/issues/762), [#795](https://github.com/fidals/shopelectro/issues/795), [#807](https://github.com/fidals/shopelectro/issues/807), [#808](https://github.com/fidals/shopelectro/issues/808) are still not solved; solved: [#761](https://github.com/fidals/shopelectro/issues/761), [#771](https://github.com/fidals/shopelectro/issues/771), [#772](https://github.com/fidals/shopelectro/issues/772), [#785](https://github.com/fidals/shopelectro/issues/785), [#799](https://github.com/fidals/shopelectro/issues/799).

**Comment by 0pdd** [comment]
@duker33 5 puzzles [#762](https://github.com/fidals/shopelectro/issues/762), [#795](https://github.com/fidals/shopelectro/issues/795), [#807](https://github.com/fidals/shopelectro/issues/807), [#920](https://github.com/fidals/shopelectro/issues/920), [#921](https://github.com/fidals/shopelectro/issues/921) are still not solved; solved: [#761](https://github.com/fidals/shopelectro/issues/761), [#771](https://github.com/fidals/shopelectro/issues/771), [#772](https://github.com/fidals/shopelectro/issues/772), [#785](https://github.com/fidals/shopelectro/issues/785), [#799](https://github.com/fidals/shopelectro/issues/799), [#808](https://github.com/fidals/shopelectro/issues/808).

**Comment by 0pdd** [comment]
@duker33 7 puzzles [#762](https://github.com/fidals/shopelectro/issues/762), [#795](https://github.com/fidals/shopelectro/issues/795), [#807](https://github.com/fidals/shopelectro/issues/807), [#920](https://github.com/fidals/shopelectro/issues/920), [#921](https://github.com/fidals/shopelectro/issues/921), [#929](https://github.com/fidals/shopelectro/issues/929), [#930](https://github.com/fidals/shopelectro/issues/930) are still not solved; solved: [#761](https://github.com/fidals/shopelectro/issues/761), [#771](https://github.com/fidals/shopelectro/issues/771), [#772](https://github.com/fidals/shopelectro/issues/772), [#785](https://github.com/fidals/shopelectro/issues/785), [#799](https://github.com/fidals/shopelectro/issues/799), [#808](https://github.com/fidals/shopelectro/issues/808).

**Comment by 0pdd** [comment]
@duker33 6 puzzles [#762](https://github.com/fidals/shopelectro/issues/762), [#795](https://github.com/fidals/shopelectro/issues/795), [#807](https://github.com/fidals/shopelectro/issues/807), [#929](https://github.com/fidals/shopelectro/issues/929), [#930](https://github.com/fidals/shopelectro/issues/930), [#938](https://github.com/fidals/shopelectro/issues/938) are still not solved; solved: [#761](https://github.com/fidals/shopelectro/issues/761), [#771](https://github.com/fidals/shopelectro/issues/771), [#772](https://github.com/fidals/shopelectro/issues/772), [#785](https://github.com/fidals/shopelectro/issues/785), [#799](https://github.com/fidals/shopelectro/issues/799), [#808](https://github.com/fidals/shopelectro/issues/808), [#920](https://github.com/fidals/shopelectro/issues/920), [#921](https://github.com/fidals/shopelectro/issues/921).

**Comment by 0pdd** [comment]
@duker33 6 puzzles [#762](https://github.com/fidals/shopelectro/issues/762), [#795](https://github.com/fidals/shopelectro/issues/795), [#807](https://github.com/fidals/shopelectro/issues/807), [#930](https://github.com/fidals/shopelectro/issues/930), [#938](https://github.com/fidals/shopelectro/issues/938), [#940](https://github.com/fidals/shopelectro/issues/940) are still not solved; solved: [#761](https://github.com/fidals/shopelectro/issues/761), [#771](https://github.com/fidals/shopelectro/issues/771), [#772](https://github.com/fidals/shopelectro/issues/772), [#785](https://github.com/fidals/shopelectro/issues/785), [#799](https://github.com/fidals/shopelectro/issues/799), [#808](https://github.com/fidals/shopelectro/issues/808), [#920](https://github.com/fidals/shopelectro/issues/920), [#921](https://github.com/fidals/shopelectro/issues/921), [#929](https://github.com/fidals/shopelectro/issues/929).

**Comment by 0pdd** [comment]
@duker33 5 puzzles [#762](https://github.com/fidals/shopelectro/issues/762), [#795](https://github.com/fidals/shopelectro/issues/795), [#807](https://github.com/fidals/shopelectro/issues/807), [#930](https://github.com/fidals/shopelectro/issues/930), [#940](https://github.com/fidals/shopelectro/issues/940) are still not solved; solved: [#761](https://github.com/fidals/shopelectro/issues/761), [#771](https://github.com/fidals/shopelectro/issues/771), [#772](https://github.com/fidals/shopelectro/issues/772), [#785](https://github.com/fidals/shopelectro/issues/785), [#799](https://github.com/fidals/shopelectro/issues/799), [#808](https://github.com/fidals/shopelectro/issues/808), [#920](https://github.com/fidals/shopelectro/issues/920), [#921](https://github.com/fidals/shopelectro/issues/921), [#929](https://github.com/fidals/shopelectro/issues/929), [#938](https://github.com/fidals/shopelectro/issues/938).
