### ISSUE TITLE
Check if Ya.Metrica is still unstable

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#766]
Problem is described at #754. We installed Sentry to collect errors.
Check Sentry's front logs. Prove whether our front has stable problems with Ya.Metric or not

**Comment by duker33** [comment]
`x2` - it's task very important for PO, so it has `x2` price

**Comment by artemiy312** [comment]
between 10th and 14th March match all orders are synced with Ya metrics.

At 9 March 2 metrics by the order page were missed.
Sentry says that adBlock blocked [one of them ](https://sentry.fidals.com/fidals/shopelectro-front/issues/59/events/2323/) and another one lost 

between 4th and 8th March match all orders are synced with Ya metrics.

At 3 March 2 metrics by the order page were missed.
Sentry says that adBlock blocked [one of them ](https://sentry.fidals.com/fidals/shopelectro-front/issues/59/events/1924/) and another one lost

**Comment by artemiy312** [comment]
I have debug the prod with this code:
```js
var r = yaCounter20644114.reachGoal;
yaCounter20644114.reachGoal = function(g) { console.log(g); r(g) } 
```

I made several test orders and metrics did not always reach the goal.

**Comment by artemiy312** [comment]
`onOrderSend` have been subscribed on `submit` which may  interfere with the goal
