### ISSUE TITLE
Cart issues on prod

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#776]
This is PO comments:

-----

заходишь на сайт, переходишь в товар. добавляешь его в корзину.  уходишь на другой товар, добавляешь его и переходишь. в корзину. ..., а его там нет

**Comment by 0pdd** [comment]
@duker33 the puzzle [#780](https://github.com/fidals/shopelectro/issues/780) is still not solved.

**Comment by 0pdd** [comment]
@duker33 the only puzzle [#780](https://github.com/fidals/shopelectro/issues/780) is solved here.
