### ISSUE TITLE
Freezed cart data on category page

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#783]
Task was created to continue with #776 

Seems PO meaned this behaviour:
- go to a category page
- put some product to cart
- see changed cart data at top-right corner
- go to any product page from current category
- click "purchase" on a product page
- go back to a previous category with breadcrums
- see an old cart data at to right-corner

**Comment by artemiy312** [comment]
@duker33 This issue mostly occurred because of http cache and redis cache.

It'd be nice to lazy-load cart data with js. It will bring ability to create shared among users cache for every catalog page and solve the issue with invalid cart data by the way.
Right now we cache category pages individually for every user and only navigation by category is shared

**Comment by duker33** [comment]
@artemiy312 , y, i thought like this too. Of course, we are needed in selenium test for the first.
And the problem solving for the second.

Hope you would like to take this task, so i assign it to you. If you wouldn't, just reassign it on me.

**Comment by 0pdd** [comment]
@duker33 2 puzzles [#788](https://github.com/fidals/shopelectro/issues/788), [#789](https://github.com/fidals/shopelectro/issues/789) are still not solved.

**Comment by 0pdd** [comment]
@duker33 4 puzzles [#788](https://github.com/fidals/shopelectro/issues/788), [#789](https://github.com/fidals/shopelectro/issues/789), [#793](https://github.com/fidals/shopelectro/issues/793), [#794](https://github.com/fidals/shopelectro/issues/794) are still not solved.

**Comment by 0pdd** [comment]
@duker33 2 puzzles [#788](https://github.com/fidals/shopelectro/issues/788), [#793](https://github.com/fidals/shopelectro/issues/793) are still not solved; solved: [#789](https://github.com/fidals/shopelectro/issues/789), [#794](https://github.com/fidals/shopelectro/issues/794).

**Comment by 0pdd** [comment]
@duker33 the puzzle [#793](https://github.com/fidals/shopelectro/issues/793) is still not solved; solved: [#788](https://github.com/fidals/shopelectro/issues/788), [#789](https://github.com/fidals/shopelectro/issues/789), [#794](https://github.com/fidals/shopelectro/issues/794).
