### ISSUE TITLE
Bad metrics collection

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#784]
Calculated month grouped orders count from DB with [this gist](https://gist.github.com/duker33/e7b7b39373452bc422fa23928ac6e40c)
For every month it's two times much, then Ya.Metrics collected (Ya.Metrics data collected PO).

Metrics is systematically wrong collected. Here we should propose a method to define where problem origins from. And maybe provide some direction to solve this problem.

The task will be implemented with research and chat discussion. It'll be resolved when we'll find a method to prove the problem's source and a direction to solve it.

**Comment by artemiy312** [comment]
We should exclude yandex orders from the result, because we didn't collect metrics for them until [this](https://github.com/fidals/shopelectro/commit/9c3edafabdb057f7cf3453ad4724fbe5a85389f5).

**Comment by duker33** [comment]
compared orders count at the DB and at the metrics at the [01.04-10.04] time interval:

souce|orders count
--|--
db|275
Ya.Ecommerce|238
Ya.Aim "Купить общая"|253

Seems metrics is not precise yet. But it's still unclear if problem is in adblocks or in smth else

**Comment by duker33** [comment]
[sentry says](https://sentry.fidals.com/fidals/shopelectro-front/issues/59/), that we are still having problems with ya.counter. But it affects only ~3% of users.
As we saw at the previous comment, we lost ~20% of orders.

So the main problem is not in the missed counter.
I propose this decision:
- we create separated task for sentry issue from the link above. Seems it's about async behavior error
- we send "Купить общая" aim event not only to Ya.Metrica, but to our backend too. It'll help us to define if it's problem in our js or Ya.Metrica servs side

**Comment by duker33** [comment]
@artemiy312 , what do you think about poins in the comment above?

If it's ok, i'll create this tasks and close this one

**Comment by artemiy312** [comment]
@duker33 

>we create separated task for sentry issue from the link above. Seems it's about async behavior error

probably it is, we should try the [same trick](https://yandex.com/support/metrica/code/counter-initialize.html#counter-initialize__tag-managment) as we [did with google analytics ](https://github.com/fidals/refarm-site/blob/master/ecommerce/front/trackers.es6#L69)

>we send "Купить общая" aim event not only to Ya.Metrica, but to our backend too. It'll help us to define if it's problem in our js or Ya.Metrica servs side

let's defer this one until we solve the issue above. Probably it would be enough

**Comment by duker33** [comment]
@artemiy312 , created #814 and assigned it to you. Hope you don't mind.
We finished this task. If problem stays, we'll create a new one or reopen this one with increased estimate.
