### ISSUE TITLE
Верни товары в  Маркет

### ISSUE THREAD

**Issue by themygit** [fidals/shopelectro#786]
Выключали товары из yml для Яндекса. Верни те, что без пометок. В них сменили фото. И они готовы к размещению.
https://docs.google.com/spreadsheets/d/1ZyDIdegU30ask4ll_Atq4KCZgN_6F6-m-3Gd8kMwD-0/edit#gid=1291240962

**Comment by duker33** [comment]
done, @themygit , you can check it on the prod
