### ISSUE TITLE
tests_selenium.py:395-397: Load the cart lazily. It will...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#789]
The puzzle `783-dbb67fb4` from #783 has to be resolved: 

https://github.com/fidals/shopelectro/blob/63cb15c122aec4ac4992e292aefcfecf5057d0b3/shopelectro/tests/tests_selenium.py#L395-L397

The puzzle was created by Artemiy on 24-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by artemiy312** [comment]
I have faced with a weird django cache issue, so i'll increase the estimate

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#793](https://github.com/fidals/shopelectro/issues/793), [#794](https://github.com/fidals/shopelectro/issues/794) are still not solved.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#793](https://github.com/fidals/shopelectro/issues/793) is still not solved; solved: [#794](https://github.com/fidals/shopelectro/issues/794).
