### ISSUE TITLE
Согласие на обработку персональных данных

### ISSUE THREAD

**Issue by themygit** [fidals/shopelectro#816]
В корзину добавляй чекбокс и текст 
http://prntscr.com/ne7yhx
Я согласен на обработку персональных данных.  
"обработку персональных данных" делай линком. 
по клику открывай пдф в новом окне 
https://www.shopelectro.ru/media/privacy-policy.pdf
чекбокс должен быть выбранным. и не несет в себе функционал. 
текст и чекбокс делай серым цветом и на 30% меньше обычного размера шрифта, что бы было плохо видно на бекграунде.

**Comment by artemiy312** [comment]
<img width="490" alt="изображение" src="https://user-images.githubusercontent.com/13870342/57042769-4f0d8800-6c6e-11e9-93ec-947946e47b51.png">

**Comment by 0pdd** [comment]
@themygit 2 puzzles [#841](https://github.com/fidals/shopelectro/issues/841), [#842](https://github.com/fidals/shopelectro/issues/842) are still not solved.

**Comment by 0pdd** [comment]
@themygit the puzzle [#842](https://github.com/fidals/shopelectro/issues/842) is still not solved; solved: [#841](https://github.com/fidals/shopelectro/issues/841).
