### ISSUE TITLE
Check google analytics features

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#818]
G.Analytics ecommerce last time worked 15.04. It's pretty the date of the last release: `0044c308ade4` fidals/se:prod image
https://analytics.google.com/analytics/web/?authuser=0#/report/conversions-ecommerce-overview/a42239144w71929328p74216659/_u.date00=20190301&_u.date01=20190422/

G.Aims not working yet. See the screen
![image](https://user-images.githubusercontent.com/3526796/56635861-b5434b00-666f-11e9-9d53-2315cda83c87.png)

**Comment by artemiy312** [comment]
It seems occurs after [this](https://github.com/fidals/refarm-site/commit/86115036b50009fb68fb80f696a836c211632cb5). Google analytics command queue isn't work as expected

**Comment by artemiy312** [comment]
I am going to revert [this changes](https://github.com/fidals/refarm-site/commit/86115036b50009fb68fb80f696a836c211632cb5) and create `onLoadName` event from GTM.
PO already have gave me credentials to GTM

**Comment by artemiy312** [comment]
Add [this](https://github.com/fidals/shopelectro/commit/374021a1b27605cc1e2a07ae8dde33769a5a5135#diff-956d9a59e5f16043e6c699973eda71f8L9) on load event dispatching to GTM

**Comment by artemiy312** [comment]
Event dispatching from GTM doesnt work, it seems because GTM loaded through iframe

**Comment by artemiy312** [comment]
@duker33 , Right now GTM injects GA to sites as html, but GTM [has an integration specificly for GA.](https://support.google.com/tagmanager/answer/6107124?hl=en&ref_topic=6333310)

The integration brings different features to work with GA among them is `dataLayer` for GA ecommerce. The feature will resolve the issue, because we won't have to sync GTM/GA/our code anymore

I'd like to use it. What do you think?

**Comment by duker33** [comment]
@artemiy312 , let's use it. It's recommended by google way to use one google service from another google service. We should not create our own solutions between them.

Subtask integration and close this task plz. Your message ahead and subtask are the good task result

**Comment by artemiy312** [comment]
Closed by https://github.com/fidals/shopelectro/issues/901
