### ISSUE TITLE
Set category as not active

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#820]
--
Убей категорию mp3 колонки. весит в меню прайсах и тд. не могу выключить.

It's possible, that seo guy can't disable it because of bug

From this doc:
https://docs.google.com/document/d/1y4xUQhQ4V_Ln5xwcEB2zMp7KTUQnkn9agKTTAU1z0-c/edit

**Comment by duker33** [comment]
> весит в меню прайсах и тд
"и тд" is very good description =)
I'll render only active categories at the excel price and on the /catalog page.
Any other place don't contain not active categories

**Comment by duker33** [comment]
it's really because of bug and i fix it at the same task

**Comment by 0pdd** [comment]
@duker33 the puzzle [#939](https://github.com/fidals/shopelectro/issues/939) is still not solved.

**Comment by 0pdd** [comment]
@duker33 the puzzle [#944](https://github.com/fidals/shopelectro/issues/944) is still not solved; solved: [#939](https://github.com/fidals/shopelectro/issues/939).
