### ISSUE TITLE
Matrix view for the catalog page

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#822]
---
Страница каталога https://www.shopelectro.ru/catalog/
Делаем по примеру https://www.220-volt.ru/catalog/ 

Три блока в строчке 
Кликабельный заголовок раздела  цвета и шрифты бери из карты товара. что бы не сливалось с подложкой. как сейчас
Первые три блока - Батарейки аккумуляторы блоки питания. выводим все подразделы. 
зарядные устройства новогодние товары измерительные приборы (по 7 подразделов второго уровня)
усилители звука беспроводные звонки радиоприемники  выводим все подразделы
Электротовары фонари автопреобразователи выводим все подразделы

From this doc:
https://docs.google.com/document/d/1y4xUQhQ4V_Ln5xwcEB2zMp7KTUQnkn9agKTTAU1z0-c/edit

**Comment by duker33** [comment]
i'll limit the cols size at the second row

**Comment by 0pdd** [comment]
@duker33 3 puzzles [#835](https://github.com/fidals/shopelectro/issues/835), [#836](https://github.com/fidals/shopelectro/issues/836), [#837](https://github.com/fidals/shopelectro/issues/837) are still not solved.

**Comment by 0pdd** [comment]
@duker33 3 puzzles [#836](https://github.com/fidals/shopelectro/issues/836), [#837](https://github.com/fidals/shopelectro/issues/837), [#851](https://github.com/fidals/shopelectro/issues/851) are still not solved; solved: [#835](https://github.com/fidals/shopelectro/issues/835).

**Comment by 0pdd** [comment]
@duker33 2 puzzles [#837](https://github.com/fidals/shopelectro/issues/837), [#851](https://github.com/fidals/shopelectro/issues/851) are still not solved; solved: [#835](https://github.com/fidals/shopelectro/issues/835), [#836](https://github.com/fidals/shopelectro/issues/836).

**Comment by 0pdd** [comment]
@duker33 3 puzzles [#851](https://github.com/fidals/shopelectro/issues/851), [#879](https://github.com/fidals/shopelectro/issues/879), [#880](https://github.com/fidals/shopelectro/issues/880) are still not solved; solved: [#835](https://github.com/fidals/shopelectro/issues/835), [#836](https://github.com/fidals/shopelectro/issues/836), [#837](https://github.com/fidals/shopelectro/issues/837).

**Comment by 0pdd** [comment]
@duker33 4 puzzles [#851](https://github.com/fidals/shopelectro/issues/851), [#879](https://github.com/fidals/shopelectro/issues/879), [#880](https://github.com/fidals/shopelectro/issues/880), [#924](https://github.com/fidals/shopelectro/issues/924) are still not solved; solved: [#835](https://github.com/fidals/shopelectro/issues/835), [#836](https://github.com/fidals/shopelectro/issues/836), [#837](https://github.com/fidals/shopelectro/issues/837).

**Comment by 0pdd** [comment]
@duker33 3 puzzles [#851](https://github.com/fidals/shopelectro/issues/851), [#879](https://github.com/fidals/shopelectro/issues/879), [#880](https://github.com/fidals/shopelectro/issues/880) are still not solved; solved: [#835](https://github.com/fidals/shopelectro/issues/835), [#836](https://github.com/fidals/shopelectro/issues/836), [#837](https://github.com/fidals/shopelectro/issues/837), [#924](https://github.com/fidals/shopelectro/issues/924).

**Comment by 0pdd** [comment]
@duker33 4 puzzles [#851](https://github.com/fidals/shopelectro/issues/851), [#879](https://github.com/fidals/shopelectro/issues/879), [#934](https://github.com/fidals/shopelectro/issues/934), [#935](https://github.com/fidals/shopelectro/issues/935) are still not solved; solved: [#835](https://github.com/fidals/shopelectro/issues/835), [#836](https://github.com/fidals/shopelectro/issues/836), [#837](https://github.com/fidals/shopelectro/issues/837), [#880](https://github.com/fidals/shopelectro/issues/880), [#924](https://github.com/fidals/shopelectro/issues/924).

**Comment by 0pdd** [comment]
@duker33 3 puzzles [#851](https://github.com/fidals/shopelectro/issues/851), [#879](https://github.com/fidals/shopelectro/issues/879), [#942](https://github.com/fidals/shopelectro/issues/942) are still not solved; solved: [#835](https://github.com/fidals/shopelectro/issues/835), [#836](https://github.com/fidals/shopelectro/issues/836), [#837](https://github.com/fidals/shopelectro/issues/837), [#880](https://github.com/fidals/shopelectro/issues/880), [#924](https://github.com/fidals/shopelectro/issues/924), [#934](https://github.com/fidals/shopelectro/issues/934), [#935](https://github.com/fidals/shopelectro/issues/935).

**Comment by 0pdd** [comment]
@duker33 2 puzzles [#851](https://github.com/fidals/shopelectro/issues/851), [#879](https://github.com/fidals/shopelectro/issues/879) are still not solved; solved: [#835](https://github.com/fidals/shopelectro/issues/835), [#836](https://github.com/fidals/shopelectro/issues/836), [#837](https://github.com/fidals/shopelectro/issues/837), [#880](https://github.com/fidals/shopelectro/issues/880), [#924](https://github.com/fidals/shopelectro/issues/924), [#934](https://github.com/fidals/shopelectro/issues/934), [#935](https://github.com/fidals/shopelectro/issues/935), [#942](https://github.com/fidals/shopelectro/issues/942).
