### ISSUE TITLE
Reorder category links in the top menu

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#823]
---
Убираем радиоприемники. расставляем как на скрине 

![image](https://user-images.githubusercontent.com/3526796/56789032-a2fd1480-6809-11e9-86e4-db107487c542.png)

From this doc:
https://docs.google.com/document/d/1y4xUQhQ4V_Ln5xwcEB2zMp7KTUQnkn9agKTTAU1z0-c/edit

**Comment by artemiy312** [comment]
Page model have a position and an active state, so we can make this fully from admin panel

@duker33 Should we make радиоприемники inactive or just hide them from header?

**Comment by duker33** [comment]
@artemiy312 , just hide them from header.
We should sort menu items in the right way. Let's do it with a settings option.
Maybe some markup issues will be raised after such sorting. For example menu items can take more then two strings after sorting

**Comment by artemiy312** [comment]
>Let's do it with a settings option.

Right now they are sorted by `position` fields, so we can just update these values to solve the issue.
@duker33  May we make it or is there any reason to avoid it?

**Comment by duker33** [comment]
@artemiy312 , let's do it. Try it directly on the prod and check if markup looks good

**Comment by artemiy312** [comment]
<img width="1045" alt="изображение" src="https://user-images.githubusercontent.com/13870342/56963952-db328900-6b62-11e9-9ed2-450238945567.png">

done
