### ISSUE TITLE
Collapse tag options by default on the mobile version

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#826]
--
В мобильной версии, когда переходишь на страницу каталога https://www.shopelectro.ru/catalog/categories/mizinchikovye-aaa-r03-lr03-fr03-286/ все свойства разкрыты по дефолту. это не удобно. делай свернутыми 

From this doc:
https://docs.google.com/document/d/1y4xUQhQ4V_Ln5xwcEB2zMp7KTUQnkn9agKTTAU1z0-c/edit

**Comment by 0pdd** [comment]
@duker33 the puzzle [#832](https://github.com/fidals/shopelectro/issues/832) is still not solved.

**Comment by 0pdd** [comment]
@duker33 the only puzzle [#832](https://github.com/fidals/shopelectro/issues/832) is solved here.
