### ISSUE TITLE
tests_selenium_admin.py:146-149: Resurrect admin price...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#835]
The puzzle `822-138e7a1d` from #822 has to be resolved: 

https://github.com/fidals/shopelectro/blob/c89b807552a45099cad752b4121f40d8836eb024/shopelectro/tests/tests_selenium_admin.py#L146-L149

The puzzle was created by duker33 on 30-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by artemiy312** [comment]
BTW drop `price` field from ProductAdminPage

**Comment by 0pdd** [comment]
@0pdd the puzzle [#851](https://github.com/fidals/shopelectro/issues/851) is still not solved.
