### ISSUE TITLE
catalog.py:43: Doc category matrix blocks.

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#837]
The puzzle `822-d2ff7292` from #822 has to be resolved: 

https://github.com/fidals/shopelectro/blob/c89b807552a45099cad752b4121f40d8836eb024/shopelectro/views/catalog.py#L43-L43

The puzzle was created by duker33 on 30-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
that's how the matrix looks like
![image](https://user-images.githubusercontent.com/3526796/59333125-64abae00-8d00-11e9-916a-79afa12fb35c.png)

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#879](https://github.com/fidals/shopelectro/issues/879), [#880](https://github.com/fidals/shopelectro/issues/880) are still not solved.

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#879](https://github.com/fidals/shopelectro/issues/879), [#880](https://github.com/fidals/shopelectro/issues/880), [#924](https://github.com/fidals/shopelectro/issues/924) are still not solved.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#879](https://github.com/fidals/shopelectro/issues/879), [#880](https://github.com/fidals/shopelectro/issues/880) are still not solved; solved: [#924](https://github.com/fidals/shopelectro/issues/924).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#879](https://github.com/fidals/shopelectro/issues/879), [#934](https://github.com/fidals/shopelectro/issues/934), [#935](https://github.com/fidals/shopelectro/issues/935) are still not solved; solved: [#880](https://github.com/fidals/shopelectro/issues/880), [#924](https://github.com/fidals/shopelectro/issues/924).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#879](https://github.com/fidals/shopelectro/issues/879), [#942](https://github.com/fidals/shopelectro/issues/942) are still not solved; solved: [#880](https://github.com/fidals/shopelectro/issues/880), [#924](https://github.com/fidals/shopelectro/issues/924), [#934](https://github.com/fidals/shopelectro/issues/934), [#935](https://github.com/fidals/shopelectro/issues/935).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#879](https://github.com/fidals/shopelectro/issues/879) is still not solved; solved: [#880](https://github.com/fidals/shopelectro/issues/880), [#924](https://github.com/fidals/shopelectro/issues/924), [#934](https://github.com/fidals/shopelectro/issues/934), [#935](https://github.com/fidals/shopelectro/issues/935), [#942](https://github.com/fidals/shopelectro/issues/942).
