### ISSUE TITLE
Fix catalog matrix columns and links

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#843]
https://www.shopelectro.ru/catalog/

- Every h2 on catalog matrix page should be clickable
- Matrix should take three columns everytime. Now it takes sometimes two, sometimes three columns
![image](https://user-images.githubusercontent.com/3526796/57689735-c10ba700-7648-11e9-9e9e-dddbabbbc272.png)

**Comment by duker33** [comment]
this markup is really about 30 mins, but i take `x2` because it's not my speciality

**Comment by 0pdd** [comment]
@duker33 the puzzle [#881](https://github.com/fidals/shopelectro/issues/881) is still not solved.

**Comment by 0pdd** [comment]
@duker33 the only puzzle [#881](https://github.com/fidals/shopelectro/issues/881) is solved here.
