### ISSUE TITLE
Fix breadcrumbs markup

### ISSUE THREAD

**Issue by artemiy312** [fidals/shopelectro#844]
https://www.shopelectro.ru/catalog/categories/zariadnye-ustroistva-242/
<img width="644" alt="изображение" src="https://user-images.githubusercontent.com/13870342/57853216-d1a95200-77ed-11e9-990e-24251f5d1b46.png">

**Comment by 0pdd** [comment]
@artemiy312 the puzzle [#849](https://github.com/fidals/shopelectro/issues/849) is still not solved.

**Comment by 0pdd** [comment]
@artemiy312 the only puzzle [#849](https://github.com/fidals/shopelectro/issues/849) is solved here.
