### ISSUE TITLE
breadcrumbs_with_siblings.html:3: Add a html validator to...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#849]
The puzzle `844-220eaf83` from #844 has to be resolved: 

https://github.com/fidals/shopelectro/blob/fb70e0d02f7b3e1946a2b56763021be28d8e17f8/templates/pages/breadcrumbs_with_siblings.html#L3-L3

The puzzle was created by Artemiy on 17-May-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
killed the task occasionally while templates refactoring. Created the new one instead
