### ISSUE TITLE
Add absolute urls to the canonical links. stb2

### ISSUE THREAD

**Issue by themygit** [fidals/shopelectro#850]
Необходимо поправить построение канонических ссылок на сайте
Адрес в канонической ссылке должен быть обязательно абсолютный
<link rel="canonical" href="https://www.сайт.ру/адрес_страницы" >
а не так
<link rel="canonical" href="/адрес_страницы" > - это неверно
Поисковики игнорируют этот тег, если указан относительный адрес в теге...
У меня при скане появляется много страниц дублей (пагинация), в коде указан каноникал. а при сканировании методом аналогичным поисковому роботу сраницы как канонические не помечаются

Вероятно, на STB нужно сделать так же.

**Comment by duker33** [comment]
at the STB resolved with https://github.com/fidals/stroyprombeton/pull/655

**Comment by 0pdd** [comment]
@themygit the puzzle [#875](https://github.com/fidals/shopelectro/issues/875) is still not solved.
