### ISSUE TITLE
битый товар. 

### ISSUE THREAD

**Issue by themygit** [fidals/shopelectro#852]
товар активный. в поиске есть. но, выдает 404 при переходе на него. 
https://www.shopelectro.ru/admin/shopelectro/productpage/9000/change/?_changelist_filters=q%3D%25D0%2591%25D0%25B0%25D1%2582%25D0%25B0%25D1%2580%25D0%25B5%25D0%25B9%25D0%25BA%25D0%25B0%2BROBITON%2BER14505-P1M2%2BLithium%252C%2B3.6%2B%25D0%2592%252C%2BAA%252C%2B2400%2B%25D0%25BC%25D0%2590%25D1%2587%2B%25D1%2581%2B%25D0%25BF%25D0%25BB%25D0%25BE%25D1%2581%25D0%25BA%25D0%25B8%25D0%25BC%25D0%25B8%2B%25D0%25B2%25D1%258B%25D0%25B2%25D0%25BE%25D0%25B4%25D0%25B0%25D0%25BC%25D0%25B8%2B%25D0%25BF%25D0%25BE%25D0%25B4%2B%25D0%25BF%25D0%25B0%25D0%25B9%25D0%25BA%25D1%2583%2BPH1

**Comment by artemiy312** [comment]
@themygit  I couldn't reproduce the issue

**Comment by themygit** [comment]
@artemiy312 he is work o_O
