### ISSUE TITLE
Fix prods content and tag filters

### ISSUE THREAD

**Issue by themygit** [fidals/shopelectro#856]
Расшифровка изображения:

------

- [x] Весы МН-267 (арт. 6882) "до 600 гр" исправить на "до 500 гр"~
- [x] На товаре [#3493](https://www.shopelectro.ru/catalog/products/3493/) стоит фото от Ansmann R14, 4500 мА

**Баги в фильтрах по тегам**

Аккумы
- [x] Panasonic Eneloop + AA - не отбирает
- [x] Panasonic Eneloop + AA + BL2 - не отбирает
- [x] Panasonic Eneloop - работает

Фонари
- [x] ручные + яркий луч - не отбирает
- [x] вело + яркий луч - не отбирает

Свинец
- [x] GS + 6В - не отбирает

Батарейки
- [x] Duracell + LR03 - не работает
- [x] Duracell + ZA312 - не работает

![WhatsApp Image 2019-05-08 at 10 08 19](https://user-images.githubusercontent.com/4608937/58330607-eb771480-7e3f-11e9-9c53-3c23bc6f24d6.jpeg)

**Comment by duker33** [comment]
i'll translate it to task

**Comment by themygit** [comment]
Убрал фотку. Поправил теги и контент у весов. Решил переписать slug тоже. в итоге поймал 500. Больше не буду трогать slug )

**Comment by duker33** [comment]
this task is just about products list filtering logic. I'll fix it with https://github.com/fidals/refarm-site/issues/338
