### ISSUE TITLE
tests_selenium_admin.py:531-533: Fix tests for...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#858]
The puzzle `827-e73e1926` from #827 has to be resolved: 

https://github.com/fidals/shopelectro/blob/39281ed9b9d945b4518b411769db4a3f454f2916/shopelectro/tests/tests_selenium_admin.py#L531-L533

The puzzle was created by Artemiy on 30-May-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by artemiy312** [comment]
>They depend on dom element positions

It seems this assumption was wrong, i forgot to add a new `Product.in_pack` field to table editor `colModel`

**Comment by 0pdd** [comment]
@0pdd the puzzle [#863](https://github.com/fidals/shopelectro/issues/863) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#863](https://github.com/fidals/shopelectro/issues/863) is solved here.
