### ISSUE TITLE
admin.es6:4: Localize Product.in_pack field

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#863]
The puzzle `858-5815cddb` from #858 has to be resolved: 

https://github.com/fidals/shopelectro/blob/cbc1a5bdcab0131ac4aa627d336b52cd7116a654/front/js/components/admin.es6#L4-L4

The puzzle was created by Artemiy on 31-May-19. 

Estimate: 15 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by artemiy312** [comment]
I am going to translate rest of field here

**Comment by artemiy312** [comment]
It seems the issue isn't related to untranslated fields. I used `make i18n`:
```
i18n:
        $(dc) run --rm app bash -c "\
                python manage.py makemessages --ignore 'venv/**' \
                && python manage.py compilemessages -l ru \
        "
```
It doesn't wait approval from user to compile messages and leads to incomplete translation and failed tests.

I am going to create todo to fix it
