### ISSUE TITLE
update_pack.py:20: Implement update_pack and render...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#864]
The puzzle `859-ae8cb052` from #859 has to be resolved: 

https://github.com/fidals/shopelectro/blob/029838cd8440741a382790fa6da0d8a790d3e423/shopelectro/management/commands/_update_catalog/update_pack.py#L20-L20

The puzzle was created by @artemiy312 on 31-May-19. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by artemiy312** [comment]
I have increased the estimate, because I made here little bit more then required

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#912](https://github.com/fidals/shopelectro/issues/912), [#913](https://github.com/fidals/shopelectro/issues/913) are still not solved.

**Comment by 0pdd** [comment]
@0pdd all 2 puzzles are solved here: [#912](https://github.com/fidals/shopelectro/issues/912), [#913](https://github.com/fidals/shopelectro/issues/913).
