### ISSUE TITLE
Удаляй категорию из YML

### ISSUE THREAD

**Issue by themygit** [fidals/shopelectro#867]
Нас забанили в мерчанте гугла, за наличие пиротехники в фиде. 
Удаляй категорию из YML
Это уже сделано для yandex.yml. Повтори для GM.yml
https://www.shopelectro.ru/catalog/categories/pirotekhnika/

**Comment by themygit** [comment]
Ближайшим фиксом. Не могу пускать трафик.

**Comment by duker33** [comment]
we have the config option for it. Fixed it on the prod
