### ISSUE TITLE
Check slug changing mech

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#868]
Slug changing on the product admin page leads to product's card 500 error.
See the comment from PO and the task for details: https://github.com/fidals/shopelectro/issues/856#issuecomment-498608200

**Comment by artemiy312** [comment]
[This](https://sentry.fidals.com/fidals/shopelectro/issues/999/?query=is:unresolved) is relevant error

**Comment by artemiy312** [comment]
The fix is arrived with [that release](https://github.com/fidals/refarm-site/releases/tag/0.6.0)
