### ISSUE TITLE
catalog.py:45-47: Improve categories matrix arch. Now...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#880]
The puzzle `837-edb24a44` from #837 has to be resolved: 

https://github.com/fidals/shopelectro/blob/bd9b654124b09163e5f1bb3a77f467fff56cffcd/shopelectro/views/catalog.py#L45-L47

The puzzle was created by duker33 on 17-Jun-19. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#924](https://github.com/fidals/shopelectro/issues/924) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#924](https://github.com/fidals/shopelectro/issues/924) is solved here.

**Comment by duker33** [comment]
may be it's related to https://github.com/fidals/stroyprombeton/issues/631

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#934](https://github.com/fidals/shopelectro/issues/934), [#935](https://github.com/fidals/shopelectro/issues/935) are still not solved; solved: [#924](https://github.com/fidals/shopelectro/issues/924).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#942](https://github.com/fidals/shopelectro/issues/942) is still not solved; solved: [#924](https://github.com/fidals/shopelectro/issues/924), [#934](https://github.com/fidals/shopelectro/issues/934), [#935](https://github.com/fidals/shopelectro/issues/935).

**Comment by 0pdd** [comment]
@0pdd all 4 puzzles are solved here: [#924](https://github.com/fidals/shopelectro/issues/924), [#934](https://github.com/fidals/shopelectro/issues/934), [#935](https://github.com/fidals/shopelectro/issues/935), [#942](https://github.com/fidals/shopelectro/issues/942).
