### ISSUE TITLE
Schedule prices updating

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#886]
According to `shopelectro/celery.py` file now we are scheduling catalog updating for every 2 hours. But not scheduling prices updating.
Schedule `price` command too. It should be launched sequentially after `update_catalog`

**Comment by duker33** [comment]
@artemiy312 , i could not find prices updating task schedule. But may be i missed smth. Approve if the schedule does not exist plz

**Comment by artemiy312** [comment]
`update_catalog` also [updates](https://github.com/fidals/shopelectro/blob/master/shopelectro/tasks.py#L61) prices
