### ISSUE TITLE
Exclude non active crums siblings

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#887]
It's screen from seo guys
![image](https://user-images.githubusercontent.com/3526796/59919299-b7d3de00-942f-11e9-8726-91307cb703be.png)

**Comment by duker33** [comment]
pretty the same issue bothers us again. I'll write the new test to identify this issue.
[Actual trello task](https://trello.com/c/5EYRzzFm/8-05-2k-%D0%B8%D1%81%D0%BA%D0%BB%D1%8E%D1%87%D0%B8-%D0%BD%D0%B5%D0%B0%D0%BA%D1%82%D0%B8%D0%B2%D0%BD%D1%8B%D0%B5-%D1%80%D0%B0%D0%B7%D0%B4%D0%B5%D0%BB%D1%8B-%D0%B8%D0%B7-%D0%BA%D1%80%D0%BE%D1%88%D0%B5%D0%BA) from the seo guys.

Small exploration at the production DB:
```
root@web:~/prog/shopelectro/docker# dcp exec app python manage.py shell -i python
Python 3.6.6 (default, Sep  5 2018, 03:44:14)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from shopelectro.models import Category
>>> Category.objects.get(id=252)
<Category: MP3- колонки>
>>> c = Category.objects.get(id=252)
>>> c.page
<Page: mp3-kolonki-252>
>>> c.page.is_active
False
>>> c.parent
>>> c.page.parent
<Page: catalog>
>>> c.page.parent
```

**Comment by duker33** [comment]
Covered the case with test, but it won't help.

Tried to remove parent 'catalog' page for the problem non-active category, but got error
```
>>> from shopelectro.models import Category
>>> c = Category.objects.get(id=252)
>>> c.page.parent = None
>>> c.page.save()
```

**Comment by duker33** [comment]
related PR now contains failed siblings mech prof test

**Comment by 0pdd** [comment]
@duker33 the puzzle [#961](https://github.com/fidals/shopelectro/issues/961) is still not solved.
