### ISSUE TITLE
Remarkup the main page

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#891]
This figma templates set contain the main page one
https://www.figma.com/file/OTnrbojXaRB0Ji6OlRR2WplG/ShopElectro?node-id=0%3A1

**Comment by 0pdd** [comment]
@duker33 the puzzle [#903](https://github.com/fidals/shopelectro/issues/903) is still not solved.

**Comment by 0pdd** [comment]
@duker33 3 puzzles [#903](https://github.com/fidals/shopelectro/issues/903), [#931](https://github.com/fidals/shopelectro/issues/931), [#932](https://github.com/fidals/shopelectro/issues/932) are still not solved.

**Comment by 0pdd** [comment]
@duker33 the puzzle [#903](https://github.com/fidals/shopelectro/issues/903) is still not solved; solved: [#931](https://github.com/fidals/shopelectro/issues/931), [#932](https://github.com/fidals/shopelectro/issues/932).
