### ISSUE TITLE
main.less:449: Markup mobile tile-about and text for main...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#903]
The puzzle `891-9180fe3b` from #891 has to be resolved: 

https://github.com/fidals/shopelectro/blob/bc1d3db1da1faa557d353c2ff9ac4dbfe9296c5c/front/less/pages/main.less#L449-L449

The puzzle was created by @duker33 on 26-Jun-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
customized styles for js

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#931](https://github.com/fidals/shopelectro/issues/931), [#932](https://github.com/fidals/shopelectro/issues/932) are still not solved.

**Comment by 0pdd** [comment]
@0pdd all 2 puzzles are solved here: [#931](https://github.com/fidals/shopelectro/issues/931), [#932](https://github.com/fidals/shopelectro/issues/932).
