### ISSUE TITLE
Fix products exclude from price

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#910]
Production config contains `7387` product excluded, but price contains the product anyway `<offer id="7387" available="true">`

**Comment by 0pdd** [comment]
@duker33 the puzzle [#914](https://github.com/fidals/shopelectro/issues/914) is still not solved.

**Comment by 0pdd** [comment]
@duker33 the only puzzle [#914](https://github.com/fidals/shopelectro/issues/914) is solved here.
