### ISSUE TITLE
update_pack.py:25-26: Raise errors in find_pack_group....

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#912]
The puzzle `864-67a30cf0` from #864 has to be resolved: 

https://github.com/fidals/shopelectro/blob/33ae939a9cc016bea33d7668aa462f03a6c73caa/shopelectro/management/commands/_update_catalog/update_pack.py#L25-L26

The puzzle was created by Artemiy on 28-Jun-19. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by artemiy312** [comment]
Closed in favor of #907
