### ISSUE TITLE
tests_commands.py:48: Test update_pack command.

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#913]
The puzzle `864-ed26e544` from #864 has to be resolved: 

https://github.com/fidals/shopelectro/blob/33ae939a9cc016bea33d7668aa462f03a6c73caa/shopelectro/tests/tests_commands.py#L48-L48

The puzzle was created by Artemiy on 28-Jun-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by artemiy312** [comment]
Closed in favor of https://github.com/fidals/shopelectro/issues/908
