### ISSUE TITLE
верни категорию в YML

### ISSUE THREAD

**Issue by themygit** [fidals/shopelectro#946]
Верни категорию в YML. Мы когда-то выключали ее. Но бизнес сказал что нужно вернуть на нее трафик. ибо выгодно. 
https://www.shopelectro.ru/catalog/categories/radiopriiomniki/

**Comment by artemiy312** [comment]
Done
```bash
~ artemiy$ curl -L https://shopelectro.ru/static/yandex.yml -0 -q 2>/dev/null | grep Радиоприёмники | wc -l
       1
```
