### ISSUE TITLE
Move PRICE_* settings to admin

### ISSUE THREAD

**Issue by artemiy312** [fidals/shopelectro#947]
We have [lot of similiar issues](https://github.com/fidals/shopelectro/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+yml) related to PRICE_* settings

**Comment by artemiy312** [comment]
@duker33 What do think? Should we make it?

**Comment by duker33** [comment]
@artemiy312 , i should we should change such settings with prod's `settings/local.py` file.
Admin approach has several disadvantages:
- the complexity with one more CRUD
- it's too hard to use for our PO or business
