### ISSUE TITLE
Верни категории в YML

### ISSUE THREAD

**Issue by themygit** [fidals/shopelectro#949]
Если нет, то верни в yml. И отпиши что добавил. 
https://www.shopelectro.ru/catalog/categories/bezmeny-elektronnye-214/
https://www.shopelectro.ru/catalog/categories/otvertki-215/
https://www.shopelectro.ru/catalog/categories/kleshchi-tokoizmeritelnye/
https://www.shopelectro.ru/catalog/categories/vattmetry/
https://www.shopelectro.ru/catalog/categories/multimetry/
https://www.shopelectro.ru/catalog/categories/testery-dlia-batareek-i-akkumuliatorov-217/
https://www.shopelectro.ru/catalog/categories/besprovodnye-zvonki-241/
https://www.shopelectro.ru/catalog/categories/fonari-226/

**Comment by duker33** [comment]
@themygit , all that stuff contained at [this category](https://www.shopelectro.ru/catalog/categories/izmeritelnye-pribory-211/):
https://www.shopelectro.ru/catalog/categories/bezmeny-elektronnye-214/
https://www.shopelectro.ru/catalog/categories/otvertki-215/
https://www.shopelectro.ru/catalog/categories/kleshchi-tokoizmeritelnye/
https://www.shopelectro.ru/catalog/categories/vattmetry/
https://www.shopelectro.ru/catalog/categories/multimetry/
https://www.shopelectro.ru/catalog/categories/testery-dlia-batareek-i-akkumuliatorov-217/

Only `Весы электронные портативные` left to exclude from price, but i included them too

**Comment by duker33** [comment]
that's full categories list we are excluding as for now:
```
PRICE_IGNORED_CATEGORIES_MAP = defaultdict(list, {
    'GM': ['Пиротехника', 'Усилители звука для слабослышащих'],
    'YM': ['Пиротехника'],
    # will be ignored by every category
    'default': [
        'Новогодние вращающиеся светодиодные лампы',
        'Новогодние лазерные проекторы', 'MP3- колонки',
    ]
})
```
