### ISSUE TITLE
Minor markup fixes 12.09

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#952]
Fixes list:
- [x] Fix [product's page markup](https://trello.com/c/oNlyfjgc/13-%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D1%91%D1%80%D1%81%D1%82%D1%8B%D0%B2%D0%B0%D0%B9-%D1%80%D0%B0%D1%81%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D0%B5-%D1%82%D0%B5%D0%BA%D1%81%D1%82%D0%B0-%D0%BD%D0%B0-%D1%82%D0%BE%D0%B2%D0%B0%D1%80%D0%B5)
- [x] Rm [redundant text](https://trello.com/c/jBEYrVz4/17-05k-%D1%83%D0%B1%D1%80%D0%B0%D1%82%D1%8C-%D0%B4%D1%83%D0%B1%D0%BB%D0%B8%D1%80%D1%83%D1%8E%D1%89%D0%B8%D0%B9%D1%81%D1%8F-%D1%82%D0%B5%D0%BA%D1%81%D1%82-%D0%BD%D0%B0-%D0%B3%D0%BB%D0%B0%D0%B2%D0%BD%D0%BE%D0%B9) at the main page
- [x] Add ["i'm agree" checkbox](https://trello.com/c/dBVHoNXs/7-05-1k-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D1%81%D0%BE%D0%B3%D0%BB%D0%B0%D1%81%D0%B8%D1%8F-%D0%BD%D0%B0-%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D1%83-%D0%BF%D0%B5%D1%80%D1%81%D0%BE%D0%BD%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D1%85-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85-%D0%B2-%D1%84%D0%BE%D1%80%D0%BC%D1%8B) to the callback form
- [x] Fix tile prices rendering [at the Firefox page](https://trello.com/c/RiDQiZTw/10-05-15k-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D0%B0-%D0%BE%D1%82%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B0-%D1%81-%D1%86%D0%B5%D0%BD%D0%B0%D0%BC%D0%B8-%D0%B2-%D0%B1%D1%80%D0%B0%D1%83%D0%B7%D0%B5%D1%80%D0%B5-firefox)

**Comment by duker33** [comment]
![image](https://user-images.githubusercontent.com/3526796/64854910-6189cc00-d627-11e9-9fa2-7a7f0d0e05ed.png)

Firefox works bad with `<input type="number">` tag with custom increase/decrease buttons.
Switching type input to text solves the problem.

Took the screen from [related trello task](https://trello.com/c/RiDQiZTw/10-05-15k-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D0%B0-%D0%BE%D1%82%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B0-%D1%81-%D1%86%D0%B5%D0%BD%D0%B0%D0%BC%D0%B8-%D0%B2-%D0%B1%D1%80%D0%B0%D1%83%D0%B7%D0%B5%D1%80%D0%B5-firefox)

**Comment by duker33** [comment]
fixed, but now counter value is not centered inside input. Styles are needed in some refactor to fix it.
Created subtask
![image](https://user-images.githubusercontent.com/3526796/64855882-81ba8a80-d629-11e9-8e83-98d85b409f34.png)

**Comment by 0pdd** [comment]
@duker33 the puzzle [#956](https://github.com/fidals/shopelectro/issues/956) is still not solved.
