### ISSUE TITLE
inputs.less:138-141: Refactor input counters Position...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#956]
The puzzle `952-c8a775a9` from #952 has to be resolved: 

https://github.com/fidals/shopelectro/blob/e9d48b7478ecb6240c090ef6cfe5c1316b345052/front/less/common/inputs.less#L138-L141

The puzzle was created by duker33 on 15-Sep-19. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
faced with connected lib styles overlapping: grid-layout or bootstrap or smth changes styles on the fly, so i can't customize them.

It'll too expensive to refactor it, so i close the task
