### ISSUE TITLE
tests_views.py:546: Repair category siblings mech.

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#961]
The puzzle `887-c7e6a145` from #887 has to be resolved: 

https://github.com/fidals/shopelectro/blob/2877085db8da5d4aab558c2f08443dbba4b50a0e/shopelectro/tests/tests_views.py#L546-L546

The puzzle was created by duker33 on 18-Sep-19. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
depends from https://github.com/fidals/refarm-site/issues/343
