### ISSUE TITLE
font-awesome.less:19-21: Fix UI issues to update...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#962]
The puzzle `894-8ab56e9d` from #894 has to be resolved: 

https://github.com/fidals/shopelectro/blob/edfb9f8a65996e24bf62d584cdea51acbc9268dc/front/less/vendors/font-awesome.less#L19-L21

The puzzle was created by @duker33 on 18-Sep-19. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
tests are working fine on the local. I'll push it to CI again
