### ISSUE TITLE
Set of seo fixes 25.09.19 

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#971]
Took them in work today 25.09.19 

Screened [SE seo-dev](https://trello.com/b/I9YKr9q4/se-seo-tasks) trello board
![image](https://user-images.githubusercontent.com/3526796/65586053-2aeb7400-df8c-11e9-90fc-ca7d8ae4b870.png)

**Comment by duker33** [comment]
contacts on small pages now looks like this:
![Uploading image.png…]()

**Comment by duker33** [comment]
stored current contacts set there
[contacts.txt](https://github.com/fidals/shopelectro/files/3651594/contacts.txt)

**Comment by 0pdd** [comment]
@duker33 2 puzzles [#974](https://github.com/fidals/shopelectro/issues/974), [#975](https://github.com/fidals/shopelectro/issues/975) are still not solved.

**Comment by 0pdd** [comment]
@duker33 4 puzzles [#974](https://github.com/fidals/shopelectro/issues/974), [#975](https://github.com/fidals/shopelectro/issues/975), [#980](https://github.com/fidals/shopelectro/issues/980), [#981](https://github.com/fidals/shopelectro/issues/981) are still not solved.

**Comment by 0pdd** [comment]
@duker33 3 puzzles [#974](https://github.com/fidals/shopelectro/issues/974), [#975](https://github.com/fidals/shopelectro/issues/975), [#981](https://github.com/fidals/shopelectro/issues/981) are still not solved; solved: [#980](https://github.com/fidals/shopelectro/issues/980).

**Comment by 0pdd** [comment]
@duker33 2 puzzles [#975](https://github.com/fidals/shopelectro/issues/975), [#981](https://github.com/fidals/shopelectro/issues/981) are still not solved; solved: [#974](https://github.com/fidals/shopelectro/issues/974), [#980](https://github.com/fidals/shopelectro/issues/980).
