### ISSUE TITLE
tile_products.html:19-20: Remove product tile cards code...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#975]
The puzzle `971-a1bdb68c` from #971 has to be resolved: 

https://github.com/fidals/shopelectro/blob/77991fd4612ae6a434e23aef3fd4d0ed83507740/templates/layout/tile_products.html#L19-L20

The puzzle was created by duker33 on 28-Sep-19. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by olegush** [comment]
Expalin the issue plz. I found the tile cards code in the tile_products.html only. And includes in product_404.html, product.html and index.html

**Comment by duker33** [comment]
@olegush , y, seems code doubling is avoided already. Plz rm the task body from the code. You can do it in one of your's already opened PRs

**Comment by duker33** [comment]
@olegush , `15 mins` is your compensation for the task

**Comment by olegush** [comment]
Done
