### ISSUE TITLE
se_extras.py:20-21: Reuse the logic.header.menu_qs menu...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#980]
The puzzle `974-ceadb5de` from #974 has to be resolved: 

https://github.com/fidals/shopelectro/blob/4da0030ab4692c401c4ff0cbcbacf947275ea369/shopelectro/templatetags/se_extras.py#L20-L21

The puzzle was created by duker33 on 30-Sep-19. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
close to get money at Oct
