### ISSUE TITLE
Has_no_category admin filter issue

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#996]
https://www.shopelectro.ru/admin/shopelectro/productpage/?all=&has_category=no

Has no category admin filter contains products that really has categories.

The first product from the screen contains category
![image](https://user-images.githubusercontent.com/3526796/66552064-5d32cf00-eb51-11e9-9e4a-2e64809f01e0.png).

[Link](https://www.shopelectro.ru/admin/shopelectro/productpage/7499/change) to the admin product

Write instruction to fill the products with missed categories with the same issue

**Comment by 0pdd** [comment]
@duker33 the puzzle [#998](https://github.com/fidals/shopelectro/issues/998) is still not solved.
